<?php
declare(strict_types=1);

function pdf_text(string $text): string{ $text=preg_replace('/[\r\n\t]+/',' ',$text)??$text;if(function_exists('iconv')){$c=@iconv('UTF-8','Windows-1252//TRANSLIT//IGNORE',$text);if($c!==false)$text=$c;}return str_replace(['\\','(',')'],['\\\\','\\(','\\)'],$text); }
function simple_pdf_document(array $lines): string
{
    $wrapped=[];foreach($lines as $line){$parts=preg_split('/\n/',wordwrap((string)$line,100,"\n",true))?:[(string)$line];foreach($parts as $part)$wrapped[]=$part;}$pages=array_chunk($wrapped?:[''],55);$pageCount=count($pages);$fontId=3+$pageCount*2;$objects=[];$kids=[];for($i=0;$i<$pageCount;$i++)$kids[]=(3+$i*2).' 0 R';$objects[1]='<< /Type /Catalog /Pages 2 0 R >>';$objects[2]='<< /Type /Pages /Kids ['.implode(' ',$kids).'] /Count '.$pageCount.' >>';foreach($pages as $i=>$pageLines){$pageId=3+$i*2;$contentId=$pageId+1;$stream="BT\n/F1 9 Tf\n40 800 Td\n12 TL\n";foreach($pageLines as $line)$stream.='('.pdf_text((string)$line).") Tj\nT*\n";$stream.="ET\n";$objects[$pageId]="<< /Type /Page /Parent 2 0 R /MediaBox [0 0 595 842] /Resources << /Font << /F1 {$fontId} 0 R >> >> /Contents {$contentId} 0 R >>";$objects[$contentId]='<< /Length '.strlen($stream)." >>\nstream\n".$stream.'endstream';}$objects[$fontId]='<< /Type /Font /Subtype /Type1 /BaseFont /Helvetica >>';ksort($objects);$pdf="%PDF-1.4\n%\xE2\xE3\xCF\xD3\n";$offsets=[0=>0];foreach($objects as $id=>$body){$offsets[$id]=strlen($pdf);$pdf.=$id." 0 obj\n".$body."\nendobj\n";}$xref=strlen($pdf);$max=max(array_keys($objects));$pdf.="xref\n0 ".($max+1)."\n0000000000 65535 f \n";for($i=1;$i<=$max;$i++)$pdf.=sprintf("%010d 00000 n \n",$offsets[$i]??0);$pdf.="trailer\n<< /Size ".($max+1)." /Root 1 0 R >>\nstartxref\n{$xref}\n%%EOF\n";return $pdf;
}
function require_report_admin(): array{return require_role(['admin']);}
function report_valid_date(string $d): bool{$x=DateTimeImmutable::createFromFormat('!Y-m-d',$d);return $x&&$x->format('Y-m-d')===$d;}
function report_range(): array{$end=(string)($_GET['endDate']??manila_today());if(!report_valid_date($end))$end=manila_today();$d=new DateTimeImmutable($end);$start=(string)($_GET['startDate']??$d->modify('-29 days')->format('Y-m-d'));return [$start,$end];}
function report_month_range(int $year,int $month): array{$first=sprintf('%04d-%02d-01',$year,$month);$d=new DateTimeImmutable($first);return [$first,$d->modify('last day of this month')->format('Y-m-d')];}
function report_rpc_rows(string $name,array $args=[]): array{$r=supabase_rpc($name,['p_args'=>$args]);return is_array($r)?$r:[];}
function report_revenue(string $start,string $end): float{$rows=report_rpc_rows('tvtms_report_revenue',[$start,$end]);return (float)($rows[0]['total']??0);}
function report_stats(array $tickets,string $start,string $end): array{$s=['total'=>count($tickets),'paid'=>0,'unpaid'=>0,'cancelled'=>0,'totalRevenue'=>report_revenue($start,$end)];foreach($tickets as $t){$st=(string)($t['status']??'');if(isset($s[$st]))$s[$st]++;}return $s;}

function reports_daily(array $params=[]): never{require_report_admin();$date=(string)($_GET['date']??manila_today());if(!report_valid_date($date))fail('Invalid date',400,'VALIDATION_ERROR');$tickets=report_rpc_rows('tvtms_report_daily_tickets',[$date]);json_response(['success'=>true,'date'=>$date,'stats'=>report_stats($tickets,$date,$date),'tickets'=>$tickets]);}
function reports_monthly(array $params=[]): never{require_report_admin();$year=(int)($_GET['year']??date('Y'));$month=(int)($_GET['month']??date('n'));if($year<2000||$year>2200||$month<1||$month>12)fail('Invalid year or month',400,'VALIDATION_ERROR');$tickets=report_rpc_rows('tvtms_report_monthly_tickets',[$year,$month]);$daily=[];foreach($tickets as $t){$d=(string)($t['date_issued']??'');$daily[$d]??=['total'=>0,'paid'=>0,'unpaid'=>0,'revenue'=>0];$daily[$d]['total']++;$st=(string)($t['status']??'');if(isset($daily[$d][$st]))$daily[$d][$st]++;}[$s,$e]=report_month_range($year,$month);foreach(report_rpc_rows('tvtms_report_daily_revenue',[$s,$e]) as $r){$d=(string)($r['collection_date']??'');$daily[$d]??=['total'=>0,'paid'=>0,'unpaid'=>0,'revenue'=>0];$daily[$d]['revenue']=(float)($r['revenue']??0);}json_response(['success'=>true,'year'=>$year,'month'=>$month,'stats'=>report_stats($tickets,$s,$e),'dailyStats'=>$daily,'tickets'=>$tickets]);}
function reports_yearly(array $params=[]): never{require_report_admin();$year=(int)($_GET['year']??date('Y'));if($year<2000||$year>2200)fail('Invalid year',400,'VALIDATION_ERROR');$tickets=report_rpc_rows('tvtms_report_yearly_tickets',[$year]);$monthly=[];foreach($tickets as $t){$m=(int)substr((string)($t['date_issued']??''),5,2);$monthly[$m]??=['total'=>0,'paid'=>0,'unpaid'=>0,'revenue'=>0];$monthly[$m]['total']++;$st=(string)($t['status']??'');if(isset($monthly[$m][$st]))$monthly[$m][$st]++;}foreach(report_rpc_rows('tvtms_report_yearly_revenue',[$year]) as $r){$m=(int)($r['month_number']??0);$monthly[$m]??=['total'=>0,'paid'=>0,'unpaid'=>0,'revenue'=>0];$monthly[$m]['revenue']=(float)($r['revenue']??0);}$s="$year-01-01";$e="$year-12-31";json_response(['success'=>true,'year'=>$year,'stats'=>report_stats($tickets,$s,$e),'monthlyStats'=>$monthly,'tickets'=>$tickets]);}
function reports_custom(array $params=[]): never{require_report_admin();$s=(string)($_GET['startDate']??'');$e=(string)($_GET['endDate']??'');if(!report_valid_date($s)||!report_valid_date($e)||$s>$e)fail('Valid startDate and endDate are required',400,'VALIDATION_ERROR');$tickets=report_rpc_rows('tvtms_report_range_tickets',[$s,$e]);json_response(['success'=>true,'startDate'=>$s,'endDate'=>$e,'stats'=>report_stats($tickets,$s,$e),'tickets'=>$tickets]);}
function reports_violations(array $params=[]): never{require_report_admin();json_response(['success'=>true,'stats'=>report_rpc_rows('tvtms_report_violation_stats',[])]);}
function reports_officers(array $params=[]): never{require_report_admin();[$s,$e]=report_range();$rows=report_rpc_rows('tvtms_report_officer_period',[$s,$e]);$p=[];foreach($rows as $r){$r['tickets_issued']=(int)($r['total_tickets']??0);$r['paid_value']=(float)($r['total_revenue']??0);$p[]=$r;}json_response(['success'=>true,'startDate'=>$s,'endDate'=>$e,'performance'=>$rows,'productivity'=>$p]);}
function reports_productivity(array $params=[]): never{reports_officers($params);}
function reports_collections(array $params=[]): never{require_report_admin();[$s,$e]=report_range();$daily=report_rpc_rows('tvtms_report_daily_collections',[$s,$e]);$overall=report_rpc_rows('tvtms_report_collections_summary',[$s,$e]);json_response(['success'=>true,'startDate'=>$s,'endDate'=>$e,'summary'=>$overall[0]??[],'dailyCollections'=>$daily]);}
function reports_hotspots(array $params=[]): never{require_report_admin();[$s,$e]=report_range();json_response(['success'=>true,'startDate'=>$s,'endDate'=>$e,'hotspots'=>report_rpc_rows('tvtms_report_hotspots',[$s,$e])]);}
function reports_officer_performance(array $params=[]): never{require_report_admin();json_response(['success'=>true,'data'=>report_rpc_rows('tvtms_report_officer_performance',[])]);}
function reports_aging(array $params=[]): never{require_report_admin();json_response(['success'=>true,'data'=>report_rpc_rows('tvtms_report_aging',[])]);}
function reports_barangay(array $params=[]): never{require_report_admin();json_response(['success'=>true,'data'=>report_rpc_rows('tvtms_report_barangay',[])]);}
function reports_analytics_collections(array $params=[]): never{require_report_admin();[$s,$e]=report_range();$daily=report_rpc_rows('tvtms_report_collections_chart',[$s,$e]);$total=report_rpc_rows('tvtms_report_collection_totals',[$s,$e]);json_response(['success'=>true,'data'=>['dailyData'=>$daily,'totalAmount'=>$total[0]['totalAmount']??0,'paymentCount'=>$total[0]['paymentCount']??0]]);}
function reports_analytics_payment_status(array $params=[]): never{require_report_admin();[$s,$e]=report_range();$breakdown=report_rpc_rows('tvtms_report_payment_status',[$s,$e]);$open=report_rpc_rows('tvtms_report_open_disputes',[$s,$e]);$r=['paid'=>0,'unpaid'=>0,'disputed'=>(int)($open[0]['disputed']??0),'cancelled'=>0];$unpaid=0;foreach($breakdown as $it){$st=(string)($it['status']??'');if(isset($r[$st]))$r[$st]=(int)($it['count']??0);if($st==='unpaid')$unpaid=(float)($it['amount']??0);}json_response(['success'=>true,'data'=>['breakdown'=>$r,'unpaidTotal'=>$unpaid,'unpaidCount'=>$r['unpaid']]]);}
function reports_analytics_tickets_summary(array $params=[]): never{require_report_admin();[$s,$e]=report_range();$total=report_rpc_rows('tvtms_report_ticket_totals',[$s,$e]);$top=report_rpc_rows('tvtms_report_top_violations',[$s,$e]);json_response(['success'=>true,'data'=>['totalIssued'=>$total[0]['totalIssued']??0,'pendingPayment'=>$total[0]['pendingPayment']??0,'topViolations'=>$top]]);}
function reports_analytics_dispute_rate(array $params=[]): never{require_report_admin();[$s,$e]=report_range();$rows=report_rpc_rows('tvtms_report_dispute_rate',[$s,$e]);$total=(int)($rows[0]['totalDisputes']??0);$resolved=(int)($rows[0]['resolvedCount']??0);json_response(['success'=>true,'data'=>['resolutionRate'=>$total?round($resolved/$total*100):0,'resolvedCount'=>$resolved,'totalDisputes'=>$total]]);}
function reports_analytics_monthly_revenue(array $params=[]): never{require_report_admin();$rows=report_rpc_rows('tvtms_report_monthly_revenue',[]);usort($rows,fn($a,$b)=>strcmp((string)($a['month']??''),(string)($b['month']??'')));json_response(['success'=>true,'data'=>$rows]);}
function reports_export(array $params=[]): never
{
    require_report_admin();$type=(string)($_GET['type']??'daily');
    if($type==='daily'){$s=$e=(string)($_GET['date']??manila_today());$tickets=report_rpc_rows('tvtms_report_daily_tickets',[$s]);$title="Daily Report - $s";}
    elseif($type==='monthly'){$y=(int)($_GET['year']??date('Y'));$m=(int)($_GET['month']??date('n'));[$s,$e]=report_month_range($y,$m);$tickets=report_rpc_rows('tvtms_report_monthly_tickets',[$y,$m]);$title='Monthly Report - '.substr($s,0,7);}
    elseif($type==='yearly'){$y=(int)($_GET['year']??date('Y'));$s="$y-01-01";$e="$y-12-31";$tickets=report_rpc_rows('tvtms_report_yearly_tickets',[$y]);$title="Yearly Report - $y";}
    elseif($type==='custom'){$s=(string)($_GET['startDate']??'');$e=(string)($_GET['endDate']??'');if(!report_valid_date($s)||!report_valid_date($e)||$s>$e)fail('startDate and endDate are required for custom report export',400,'VALIDATION_ERROR');$tickets=report_rpc_rows('tvtms_report_range_tickets',[$s,$e]);$title="Custom Report - $s to $e";}
    else fail('Invalid report type',400,'VALIDATION_ERROR');
    if(!report_valid_date($s)||!report_valid_date($e))fail('Invalid report date range',400,'VALIDATION_ERROR');$stats=report_stats($tickets,$s,$e);$settingRows=report_rpc_rows('tvtms_report_settings',[]);$settings=[];foreach($settingRows as $r)$settings[(string)($r['setting_key']??'')]=$r['setting_value']??'';
    $lines=[$settings['system_title']??'Traffic Violation Ticketing and Management System',($settings['lgu_name']??'Municipality of Calape').' - Traffic Enforcement Division',trim(($settings['lgu_address']??'Calape, Bohol').' '.($settings['lgu_contact']??'')),'',$title,'Generated: '.date('Y-m-d H:i:s'),'',$stats['total'].' Total Tickets | '.$stats['paid'].' Paid | '.$stats['unpaid'].' Unpaid | '.$stats['cancelled'].' Cancelled','Total Revenue: PHP '.number_format((float)$stats['totalRevenue'],2),'','Ticket Details'];
    if(!$tickets)$lines[]='No tickets found for the selected period.';foreach(array_slice($tickets,0,500) as $i=>$t)$lines[]=($i+1).'. '.($t['ticket_number']??'').' | '.($t['date_issued']??'').' | '.($t['plate_number']??'').' | '.($t['violation_name']??'').' | PHP '.number_format((float)($t['penalty_amount']??0),2).' | '.($t['status']??'');
    $pdf=simple_pdf_document($lines);$filename=preg_replace('/[^a-z0-9_-]/i','-',$type).'-report-'.manila_today().'.pdf';header('Content-Type: application/pdf');header('Content-Disposition: attachment; filename="'.$filename.'"');header('Content-Length: '.strlen($pdf));echo $pdf;exit;
}
