<?php
declare(strict_types=1);
function violations_list(array $params=[]): never{$u=require_role(['admin','apprehending_officer']);$rows=supabase_select('violations',[],['select'=>'*','order'=>'violation_code.asc','limit'=>1000]);json_response(['success'=>true,'violations'=>$rows,'data'=>$rows]);}
function violations_active(array $params=[]): never{$u=require_role(['admin','apprehending_officer']);$rows=supabase_select('violations',['status'=>'eq.active','is_citation_selectable'=>'eq.true'],['select'=>'*','order'=>'violation_name.asc,id.asc','limit'=>1000]);json_response(['success'=>true,'violations'=>$rows,'data'=>$rows]);}
function violations_get_one(array $params): never{$u=require_role(['admin','apprehending_officer']);$id=(int)$params['id'];$rows=supabase_select('violations',['id'=>'eq.'.$id],['select'=>'*','limit'=>1]);if(!$rows)fail('Violation not found',404,'VIOLATION_NOT_FOUND');json_response(['success'=>true,'violation'=>$rows[0],'data'=>$rows[0]]);}
function violations_penalty_preview(array $params): never{$u=require_role(['admin','apprehending_officer']);$id=(int)$params['id'];$plate=normalize_plate($_GET['plateNumber']??$_GET['plate_number']??'');if($plate==='')fail('plateNumber is required',400,'VALIDATION_ERROR');$rows=supabase_select('violations',['id'=>'eq.'.$id,'status'=>'eq.active','is_citation_selectable'=>'eq.true'],['select'=>'id,violation_code,violation_name,penalty_amount','limit'=>1]);if(!$rows)fail('Violation unavailable for citation',404,'VIOLATION_UNAVAILABLE');$v=$rows[0];$history=supabase_rpc('tvtms_catalog_prior_offenses',['p_id'=>$id,'p_plate'=>$plate]);$prior=(int)($history['prior_count']??0);$next=$prior+1;$base=(float)$v['penalty_amount'];$effective=$base;$used=false;$effective=(float)supabase_rpc('tvtms_citation_penalty',[]);json_response(['success'=>true,'penalty'=>['violationId'=>$id,'violationCode'=>$v['violation_code'],'violationName'=>$v['violation_name'],'plateNumber'=>$plate,'priorOffenseCount'=>$prior,'nextOffenseCount'=>$next,'basePenalty'=>$base,'effectivePenalty'=>$effective,'usedEscalationRule'=>$used]]);}
function violations_create(array $params=[]): never{$u=require_role(['admin']);$in=json_input();if(!empty($in['is_citation_selectable']))fail('The official citation checklist is protected.',409,'OFFICIAL_CATALOG_PROTECTED');$code=strtoupper(clean_string($in['violation_code']??'',20));$name=clean_string($in['violation_name']??'',150);$description=clean_string($in['description']??'',4000);$penalty=(float)supabase_rpc('tvtms_citation_penalty',[]);$points=(int)($in['demerit_points']??0);if(!preg_match('/^[A-Z0-9_-]{2,20}$/',$code)||$name===''||$penalty<=0||$penalty>10000000||$points<0||$points>100)fail('Provide a valid code, name, positive penalty amount, and demerit points from 0 to 100.',400,'VALIDATION_ERROR');if(supabase_select('violations',['violation_code'=>'eq.'.$code],['select'=>'id','limit'=>1]))fail('Violation code already exists',409,'DUPLICATE_CODE');$rows=supabase_insert('violations',[['violation_code'=>$code,'violation_name'=>$name,'description'=>$description?:null,'penalty_amount'=>$penalty,'demerit_points'=>$points,'status'=>'active','requires_description'=>!empty($in['requires_description'])]]);$id=(int)($rows[0]['id']??0);log_audit((int)$u['id'],'VIOLATION_CREATED','violations',$id,['violationCode'=>$code,'penaltyAmount'=>$penalty,'demeritPoints'=>$points]);json_response(['success'=>true,'message'=>'Violation created successfully','violationId'=>$id],201);}
function violations_update(array $params): never{$u=require_role(['admin']);$id=(int)$params['id'];$rows=supabase_select('violations',['id'=>'eq.'.$id],['select'=>'*','limit'=>1]);if(!$rows)fail('Violation not found',404,'VIOLATION_NOT_FOUND');$cur=$rows[0];$in=json_input();protect_official_violation_input($cur,$in);$code=strtoupper(clean_string($in['violation_code']??$cur['violation_code'],20));$name=clean_string($in['violation_name']??$cur['violation_name'],150);$description=clean_string($in['description']??($cur['description']??''),4000);$penalty=(float)supabase_rpc('tvtms_citation_penalty',[]);$points=(int)($in['demerit_points']??$cur['demerit_points']);$status=strtolower((string)($in['status']??$cur['status']));if(!preg_match('/^[A-Z0-9_-]{2,20}$/',$code)||$name===''||$penalty<=0||$penalty>10000000||$points<0||$points>100||!in_array($status,['active','inactive'],true))fail('One or more violation fields are invalid.',400,'VALIDATION_ERROR');try{supabase_update('violations',['violation_code'=>$code,'violation_name'=>$name,'description'=>$description?:null,'penalty_amount'=>$penalty,'demerit_points'=>$points,'status'=>$status,'requires_description'=>array_key_exists('requires_description',$in)?!empty($in['requires_description']):$cur['requires_description']],['id'=>'eq.'.$id],false);}catch(SupabaseException $e){if($e->pgCode==='23505')fail('Violation code already exists',409,'DUPLICATE_CODE');throw $e;}log_audit((int)$u['id'],'VIOLATION_UPDATED','violations',$id,['violationCode'=>$code,'penaltyAmount'=>$penalty,'demeritPoints'=>$points,'status'=>$status]);json_response(['success'=>true,'message'=>'Violation updated successfully']);}
function violations_delete(array $params): never{$u=require_role(['admin']);$id=(int)$params['id'];$rows=supabase_select('violations',['id'=>'eq.'.$id],['select'=>'is_citation_selectable','limit'=>1]);if(!empty($rows[0]['is_citation_selectable']))fail('Official citation choices cannot be deleted.',409,'OFFICIAL_CATALOG_PROTECTED');$out=supabase_rpc('tvtms_catalog_delete_violation',['p_id'=>$id]);if(is_array($out)&&isset($out['error']))fail((string)$out['error'],(int)($out['status']??409),'VIOLATION_DELETE_REJECTED');log_audit((int)$u['id'],'VIOLATION_DELETED','violations',$id);json_response(['success'=>true,'message'=>'Violation deleted successfully']);}

function protect_official_violation_input(array $current, array $input): void
{
    foreach (['is_citation_selectable','violation_code','violation_name','status','requires_description'] as $field) {
        if (!array_key_exists($field,$input)) continue;
        if ($field !== 'is_citation_selectable' && empty($current['is_citation_selectable'])) continue;
        $value=$input[$field]; $stored=$current[$field]??null;
        if (in_array($field,['is_citation_selectable','requires_description'],true)) {
            $changed=!is_bool($value) || $value !== (bool)$stored;
        } else {
            $changed=!is_string($value) || trim($value) !== (string)$stored;
        }
        if ($changed) fail('Official citation identity and selection behavior are protected.',409,'OFFICIAL_CATALOG_PROTECTED');
    }
}
