import { useEffect, useState } from 'react';
import { API } from '../services/api';
import DataTable from '../components/DataTable';
import StatusBadge from '../components/StatusBadge';
import Notice from '../components/Notice';
import Modal from '../components/Modal';
import Icon from '../components/Icon';
import { firstArray, money } from '../utils/format';
const blank={violation_code:'',violation_name:'',description:'',penalty_amount:'',requires_description:false,demerit_points:0,status:'active'};
export default function ManageViolations(){
 const [rows,setRows]=useState([]);const [form,setForm]=useState(blank);const [editing,setEditing]=useState(null);const [open,setOpen]=useState(false);const [notice,setNotice]=useState({type:'',text:''});
 const official = Boolean(editing?.is_citation_selectable);
 const load=()=>API.violations().then(response=>setRows(firstArray(response,['violations']))).catch(error=>setNotice({type:'error',text:error.message}));useEffect(()=>{load();},[]);
 const start=row=>{setEditing(row||null);setForm(row?{...blank,...row}:blank);setOpen(true);};
 const save=async()=>{try{const payload={...form,penalty_amount:Number(form.penalty_amount),demerit_points:Number(form.demerit_points)};if(editing)await API.updateViolation(editing.id,payload);else await API.createViolation(payload);setOpen(false);await load();setNotice({type:'success',text:editing?'Violation updated.':'Violation created.'});}catch(error){setNotice({type:'error',text:error.message});}};
 const remove=async row=>{if(!confirm(`Delete ${row.violation_code}? Existing ticket references will prevent deletion.`))return;try{await API.deleteViolation(row.id);await load();}catch(error){setNotice({type:'error',text:error.message});}};
 const columns=[{key:'violation_code',label:'Code'},{key:'violation_name',label:'Violation'},{key:'penalty_amount',label:'Penalty',render:row=>money(row.penalty_amount)},{key:'is_citation_selectable',label:'Catalog',render:row=>row.is_citation_selectable?'Official citation choice':'Legacy / Admin'},{key:'demerit_points',label:'Demerit'},{key:'status',label:'Status',render:row=><StatusBadge value={row.status}/>},{key:'actions',label:'Actions',render:row=><div className="table-actions"><button className="text-link" onClick={event=>{event.stopPropagation();start(row);}}>Edit</button><button disabled={row.is_citation_selectable} title={row.is_citation_selectable?'Official citation choice is protected':undefined} className="text-link danger-link" onClick={event=>{event.stopPropagation();remove(row);}}>Delete</button></div>}];
 return <div className="restored-management-page"><Notice type={notice.type}>{notice.text}</Notice><section className="card"><div className="card-header management-card-header"><div><h3 className="card-title">Violation Types</h3><p>The 18 official citation choices are protected. Maintain legacy entries and descriptive metadata. The configured flat penalty applies to every violation.</p></div><button className="btn btn-primary" onClick={()=>start(null)}><Icon name="plus"/> Add New Violation</button></div><div className="card-body"><DataTable columns={columns} rows={rows}/></div></section><Modal open={open} title={editing?'Edit Violation':'Add New Violation'} onClose={()=>setOpen(false)} footer={<><button className="btn btn-secondary" onClick={()=>setOpen(false)}>Cancel</button><button className="btn btn-primary" onClick={save}>Save</button></>}><div className="form-grid">{official&&<p className="span-2">Official citation choice: code, name, status, and description requirement are protected by the server.</p>}<label className="field"><span>Code</span><input required disabled={official} value={form.violation_code} onChange={event=>setForm({...form,violation_code:event.target.value.toUpperCase()})}/></label><label className="field"><span>Name</span><input required disabled={official} value={form.violation_name} onChange={event=>setForm({...form,violation_name:event.target.value})}/></label><label className="field"><span>Penalty amount</span><input readOnly value={editing?money(form.penalty_amount):'Configured flat penalty (set by server)'}/><small>History does not increase this penalty.</small></label><label className="field"><span>Demerit points</span><input type="number" min="0" value={form.demerit_points} onChange={event=>setForm({...form,demerit_points:event.target.value})}/></label><label className="field span-2"><span><input type="checkbox" disabled={official} checked={form.requires_description} onChange={event=>setForm({...form,requires_description:event.target.checked})}/> Require an additional description when selected (e.g. Others)</span></label><label className="field span-2"><span>Description</span><textarea rows="4" value={form.description||''} onChange={event=>setForm({...form,description:event.target.value})}/></label>{editing&&<label className="field"><span>Status</span><select disabled={official} value={form.status} onChange={event=>setForm({...form,status:event.target.value})}><option value="active">Active</option><option value="inactive">Inactive</option></select></label>}</div></Modal></div>;
}
