-- PostgreSQL 17 / Supabase production schema for TVTMS.
-- The Express API connects privately; browser clients must never receive the database secret.

create schema if not exists private;
revoke all on schema private from public, anon, authenticated;

create or replace function private.set_updated_at()
returns trigger
language plpgsql
security invoker
set search_path = ''
as $$
begin
  new.updated_at = current_timestamp;
  return new;
end;
$$;
revoke all on function private.set_updated_at() from public, anon, authenticated;

create table if not exists public.users (
  id bigint generated by default as identity primary key,
  name varchar(100) not null,
  email varchar(100) unique not null,
  password varchar(255) not null,
  -- `driver` is retained only for legacy record integrity; the API rejects it at login.
  role varchar(30) not null default 'apprehending_officer' check (role in ('admin','apprehending_officer','driver')),
  contact_number varchar(20),
  plate_number varchar(20),
  status varchar(20) not null default 'active' check (status in ('active','inactive')),
  failed_login_attempts integer not null default 0,
  locked_until timestamptz,
  reset_token_hash varchar(64),
  reset_token_expires timestamptz,
  last_login timestamptz,
  created_at timestamptz not null default current_timestamp,
  updated_at timestamptz not null default current_timestamp
);

create table if not exists public.owners (
  id bigint generated by default as identity primary key,
  name varchar(100),
  email varchar(100),
  address text,
  contact_number varchar(20),
  created_at timestamptz not null default current_timestamp,
  updated_at timestamptz not null default current_timestamp
);

create table if not exists public.vehicles (
  id bigint generated by default as identity primary key,
  plate_number varchar(20) unique not null,
  vehicle_type varchar(20) not null check (vehicle_type in ('motorcycle','tricycle','car','truck','bus','van')),
  owner_name varchar(100),
  owner_email varchar(100),
  driver_license_number varchar(30),
  owner_address text,
  owner_id bigint references public.owners(id) on delete set null,
  created_at timestamptz not null default current_timestamp,
  updated_at timestamptz not null default current_timestamp
);

create table if not exists public.violations (
  id bigint generated by default as identity primary key,
  violation_code varchar(20) unique not null,
  violation_name varchar(150) not null,
  description text,
  penalty_amount numeric(10,2) not null check (penalty_amount >= 0),
  demerit_points integer not null default 0 check (demerit_points >= 0),
  status varchar(20) not null default 'active' check (status in ('active','inactive')),
  created_at timestamptz not null default current_timestamp,
  updated_at timestamptz not null default current_timestamp
);

create table if not exists public.violation_penalty_rules (
  id bigint generated by default as identity primary key,
  violation_id bigint not null references public.violations(id) on delete cascade,
  offense_count integer not null check (offense_count > 0),
  penalty_amount numeric(10,2) not null check (penalty_amount >= 0),
  is_active smallint not null default 1 check (is_active in (0,1)),
  effective_from date not null,
  effective_to date,
  created_at timestamptz not null default current_timestamp,
  updated_at timestamptz not null default current_timestamp
);

create table if not exists public.tickets (
  id bigint generated by default as identity primary key,
  ticket_number varchar(30) unique not null,
  user_id bigint not null references public.users(id) on delete restrict,
  vehicle_id bigint not null references public.vehicles(id) on delete restrict,
  violation_id bigint not null references public.violations(id) on delete restrict,
  owner_name_at_issue varchar(100),
  owner_email_at_issue varchar(100),
  owner_address_at_issue text,
  penalty_amount_at_issue numeric(10,2),
  date_issued date not null,
  time_issued time not null,
  location varchar(200),
  remarks text,
  status varchar(20) not null default 'unpaid' check (status in ('unpaid','paid','cancelled')),
  payment_date date,
  created_at timestamptz not null default current_timestamp,
  updated_at timestamptz not null default current_timestamp
);

create table if not exists public.ticket_number_sequences (
  sequence_year smallint primary key,
  last_number integer not null default 0,
  updated_at timestamptz not null default current_timestamp
);

create table if not exists public.ticket_status_history (
  id bigint generated by default as identity primary key,
  ticket_id bigint not null references public.tickets(id) on delete cascade,
  previous_status varchar(30),
  new_status varchar(30) not null,
  changed_by bigint not null references public.users(id) on delete restrict,
  reason text,
  approver_id bigint references public.users(id) on delete set null,
  created_at timestamptz not null default current_timestamp
);

create table if not exists public.payments (
  id bigint generated by default as identity primary key,
  ticket_id bigint not null references public.tickets(id) on delete restrict,
  amount_paid numeric(10,2) not null check (amount_paid > 0),
  official_receipt_number varchar(50) unique not null,
  payment_method varchar(20) not null default 'cash' check (payment_method in ('cash','gcash','maya','bank_transfer','other')),
  payment_status varchar(20) not null default 'full' check (payment_status in ('partial','full','voided')),
  payment_date date not null,
  notes text,
  recorded_by bigint references public.users(id) on delete set null,
  created_at timestamptz not null default current_timestamp,
  updated_at timestamptz not null default current_timestamp
);

create table if not exists public.disputes (
  id bigint generated by default as identity primary key,
  ticket_id bigint not null references public.tickets(id) on delete restrict,
  submitted_by bigint references public.users(id) on delete restrict,
  contact_name varchar(120),
  contact_email varchar(190),
  submission_source varchar(20) not null default 'internal' check (submission_source in ('internal','public')),
  reason text not null,
  status varchar(20) not null default 'submitted' check (status in ('submitted','under_review','approved','rejected','closed')),
  resolution_notes text,
  resolved_by bigint references public.users(id) on delete set null,
  resolved_at timestamptz,
  created_at timestamptz not null default current_timestamp,
  updated_at timestamptz not null default current_timestamp
);

create table if not exists public.evidence (
  id bigint generated by default as identity primary key,
  ticket_id bigint not null references public.tickets(id) on delete cascade,
  file_path varchar(255) not null,
  file_name varchar(255),
  file_type varchar(50),
  file_size integer check (file_size is null or (file_size >= 0 and file_size <= 5242880)),
  uploaded_by bigint not null references public.users(id) on delete restrict,
  gps_lat numeric(10,7) check (gps_lat is null or gps_lat between -90 and 90),
  gps_lng numeric(10,7) check (gps_lng is null or gps_lng between -180 and 180),
  file_data bytea,
  created_at timestamptz not null default current_timestamp
);

create table if not exists public.notifications (
  id bigint generated by default as identity primary key,
  user_id bigint not null references public.users(id) on delete cascade,
  type varchar(50) not null,
  title varchar(150) not null,
  message text,
  is_read smallint not null default 0 check (is_read in (0,1)),
  read_at timestamptz,
  reference_type varchar(50),
  reference_id bigint,
  created_at timestamptz not null default current_timestamp
);

create table if not exists public.contact_messages (
  id bigint generated by default as identity primary key,
  full_name varchar(120) not null,
  email varchar(190) not null,
  subject varchar(150) not null,
  message text not null,
  status varchar(20) not null default 'new' check (status in ('new','read','archived')),
  created_at timestamptz not null default current_timestamp
);

create table if not exists public.audit_logs (
  id bigint generated by default as identity primary key,
  user_id bigint references public.users(id) on delete set null,
  action varchar(100) not null,
  entity_type varchar(50),
  entity_id bigint,
  metadata text,
  ip_address varchar(45),
  user_agent text,
  created_at timestamptz not null default current_timestamp
);

create table if not exists public.system_settings (
  id bigint generated by default as identity primary key,
  setting_key varchar(100) unique not null,
  setting_value text,
  description text,
  updated_at timestamptz not null default current_timestamp
);

create index if not exists idx_users_role on public.users(role);
create index if not exists idx_users_plate_number on public.users(plate_number);
create index if not exists idx_owner_email on public.owners(email);
create index if not exists idx_vehicle_owner_id on public.vehicles(owner_id);
create index if not exists idx_penalty_rule_violation_id on public.violation_penalty_rules(violation_id);
create index if not exists idx_ticket_status on public.tickets(status);
create index if not exists idx_ticket_date on public.tickets(date_issued);
create index if not exists idx_ticket_user_date on public.tickets(user_id, date_issued desc);
create index if not exists idx_ticket_vehicle_id on public.tickets(vehicle_id);
create index if not exists idx_ticket_violation_id on public.tickets(violation_id);
create index if not exists idx_history_ticket_created on public.ticket_status_history(ticket_id, created_at);
create index if not exists idx_history_changed_by on public.ticket_status_history(changed_by);
create index if not exists idx_history_approver_id on public.ticket_status_history(approver_id) where approver_id is not null;
create index if not exists idx_payment_status on public.payments(payment_status);
create index if not exists idx_payment_ticket_date on public.payments(ticket_id, payment_date desc);
create index if not exists idx_payment_recorded_by on public.payments(recorded_by);
create index if not exists idx_dispute_ticket_status on public.disputes(ticket_id, status);
create index if not exists idx_dispute_submitted_by on public.disputes(submitted_by) where submitted_by is not null;
create index if not exists idx_dispute_resolved_by on public.disputes(resolved_by) where resolved_by is not null;
create index if not exists idx_evidence_ticket_created on public.evidence(ticket_id, created_at desc);
create index if not exists idx_evidence_uploaded_by on public.evidence(uploaded_by);
create index if not exists idx_contact_status_created on public.contact_messages(status, created_at);
create index if not exists idx_contact_email on public.contact_messages(email);
create index if not exists idx_audit_action on public.audit_logs(action);
create index if not exists idx_audit_created on public.audit_logs(created_at);
create index if not exists idx_audit_user_id on public.audit_logs(user_id) where user_id is not null;
create index if not exists idx_notification_user_created on public.notifications(user_id, created_at desc);

drop trigger if exists users_updated_at on public.users;
create trigger users_updated_at before update on public.users for each row execute function private.set_updated_at();
drop trigger if exists owners_updated_at on public.owners;
create trigger owners_updated_at before update on public.owners for each row execute function private.set_updated_at();
drop trigger if exists vehicles_updated_at on public.vehicles;
create trigger vehicles_updated_at before update on public.vehicles for each row execute function private.set_updated_at();
drop trigger if exists violations_updated_at on public.violations;
create trigger violations_updated_at before update on public.violations for each row execute function private.set_updated_at();
drop trigger if exists penalty_rules_updated_at on public.violation_penalty_rules;
create trigger penalty_rules_updated_at before update on public.violation_penalty_rules for each row execute function private.set_updated_at();
drop trigger if exists tickets_updated_at on public.tickets;
create trigger tickets_updated_at before update on public.tickets for each row execute function private.set_updated_at();
drop trigger if exists payments_updated_at on public.payments;
create trigger payments_updated_at before update on public.payments for each row execute function private.set_updated_at();
drop trigger if exists disputes_updated_at on public.disputes;
create trigger disputes_updated_at before update on public.disputes for each row execute function private.set_updated_at();
drop trigger if exists settings_updated_at on public.system_settings;
create trigger settings_updated_at before update on public.system_settings for each row execute function private.set_updated_at();

create or replace view public.ticket_details with (security_invoker = true) as
select t.id,t.ticket_number,t.date_issued,t.time_issued,t.location,t.status,t.payment_date,t.user_id,
       coalesce(t.penalty_amount_at_issue,viol.penalty_amount) as penalty_amount,t.penalty_amount_at_issue,
       u.name as officer_name,v.plate_number,v.vehicle_type,
       coalesce(t.owner_name_at_issue,v.owner_name) as owner_name,
       coalesce(t.owner_email_at_issue,v.owner_email) as owner_email,
       coalesce(t.owner_address_at_issue,v.owner_address) as owner_address,
       v.driver_license_number,viol.violation_code,viol.violation_name,viol.demerit_points
from public.tickets t
join public.users u on t.user_id=u.id
join public.vehicles v on t.vehicle_id=v.id
join public.violations viol on t.violation_id=viol.id;

create or replace view public.daily_stats with (security_invoker = true) as
select date_issued as date,count(*) as total_tickets,
       sum(case when status='paid' then 1 else 0 end) as paid_tickets,
       sum(case when status='unpaid' then 1 else 0 end) as unpaid_tickets,
       sum(case when status='cancelled' then 1 else 0 end) as cancelled_tickets
from public.tickets group by date_issued;

insert into public.violations(violation_code,violation_name,description,penalty_amount,demerit_points) values
('V001','No Helmet','Driver or passenger not wearing helmet within municipality',500.00,3),
('V002','No License','Driving without valid license within LGU jurisdiction',1000.00,5),
('V003','No Registration','Vehicle not registered or expired registration',2000.00,5),
('V004','Overspeeding','Exceeding municipal speed limit',1000.00,4),
('V005','Reckless Driving','Driving in a reckless manner on local roads',2000.00,6),
('V006','Invalid Plate Number','Using invalid or tampered plate number',2000.00,5),
('V007','Triple Riding','More than two persons on a motorcycle',500.00,2),
('V008','Illegal Parking','Parking in area prohibited by local ordinance',300.00,1),
('V009','No Signal Light','Not using signal lights when turning on local roads',300.00,1),
('V010','Swerving','Abrupt lane changing without signal',500.00,2),
('V011','Counterflow','Driving against traffic flow on local roads',1000.00,4),
('V012','Disregarding Traffic Signs','Ignoring local traffic signs and signals',500.00,3),
('V013','Using Mobile Phone While Driving','Using mobile phone while driving on local roads',500.00,2),
('V014','No Side Mirror','Operating vehicle without side mirrors',300.00,1),
('V015','Defective Lights','Broken or non-functional headlights/taillights',500.00,2)
on conflict (violation_code) do nothing;

insert into public.system_settings(setting_key,setting_value,description) values
('lgu_name','Municipality of Calape','Name of the LGU'),
('lgu_address','Calape, Bohol','Address of the LGU'),
('lgu_contact','','Official LGU contact number'),
('dispute_deadline_days','15','Number of days allowed for filing a dispute'),
('system_title','Municipal Traffic Violation Ticketing and Management System','System title shown in headers and reports'),
('payment_deadline_days','30','Number of days before a ticket is considered overdue'),
('send_violation_notice','1','Send violation notice emails when SMTP is configured'),
('send_payment_confirmation','1','Send payment confirmation emails when SMTP is configured')
on conflict (setting_key) do nothing;

do $$
declare table_name text;
begin
  foreach table_name in array array['users','owners','vehicles','violations','violation_penalty_rules','tickets',
    'ticket_number_sequences','ticket_status_history','payments','disputes','evidence','notifications',
    'contact_messages','audit_logs','system_settings']
  loop
    execute format('alter table public.%I enable row level security', table_name);
    execute format('revoke all on table public.%I from anon, authenticated, service_role', table_name);
  end loop;
end $$;
revoke all on table public.ticket_details, public.daily_stats from anon, authenticated, service_role;
revoke all on all sequences in schema public from anon, authenticated, service_role;
revoke all on all functions in schema public from public, anon, authenticated, service_role;

alter default privileges for role postgres in schema public
  revoke select, insert, update, delete on tables from anon, authenticated, service_role;
alter default privileges for role postgres in schema public
  revoke execute on functions from public, anon, authenticated, service_role;
alter default privileges for role postgres in schema public
  revoke usage, select on sequences from anon, authenticated, service_role;
