import { useEffect, useState } from 'react';
import { API } from '../services/api';
import Notice from '../components/Notice';
import Icon from '../components/Icon';
const keys=['system_title','lgu_name','lgu_address','lgu_contact','dispute_deadline_days','payment_deadline_days','send_violation_notice','send_payment_confirmation'];

export default function AdminSettings(){
  const [values,setValues]=useState({});const [notice,setNotice]=useState({type:'',text:''});const [busy,setBusy]=useState(false);
  useEffect(()=>{API.settings().then(response=>{const rows=response.settings||response.data||[];setValues(Object.fromEntries(rows.map(setting=>[setting.setting_key,setting.setting_value])));}).catch(error=>setNotice({type:'error',text:error.message}));},[]);
  const save=async()=>{setBusy(true);try{await API.updateSettings({settings:Object.fromEntries(keys.map(key=>[key,values[key]??'']))});setNotice({type:'success',text:'System settings updated.'});}catch(error){setNotice({type:'error',text:error.message});}finally{setBusy(false);}};
  const checked=key=>String(values[key])==='1';
  return <div className="restored-settings-page">
    <section className="card profile-hero-card"><div className="card-body profile-hero-content"><div><p className="section-kicker">Configuration</p><h3 className="card-title">Manage verified system preferences</h3><p>Update LGU identity, public deadlines, and supported email notifications.</p></div></div></section>
    <Notice type={notice.type}>{notice.text}</Notice>

    <section className="card settings-section"><div className="card-header"><h3 className="card-title"><Icon name="settings"/> LGU Information</h3></div><div className="card-body"><p className="settings-note">These values appear in generated reports and supported email messages.</p><div className="settings-grid"><label className="settings-field"><span>LGU Name</span><input value={values.lgu_name||''} onChange={event=>setValues({...values,lgu_name:event.target.value})}/></label><label className="settings-field"><span>System Title</span><input value={values.system_title||''} onChange={event=>setValues({...values,system_title:event.target.value})}/></label><label className="settings-field"><span>Contact Number</span><input value={values.lgu_contact||''} onChange={event=>setValues({...values,lgu_contact:event.target.value})}/></label><label className="settings-field"><span>LGU Address</span><input value={values.lgu_address||''} onChange={event=>setValues({...values,lgu_address:event.target.value})}/></label></div><div className="settings-actions"><button className="btn btn-primary" onClick={save} disabled={busy}>Save LGU Information</button></div></div></section>

    <section className="card settings-section"><div className="card-header"><h3 className="card-title"><Icon name="clock"/> Filing and Payment Deadlines</h3></div><div className="card-body"><div className="settings-grid"><label className="settings-field"><span>Dispute Filing Deadline (days)</span><input type="number" min="1" max="365" value={values.dispute_deadline_days||15} onChange={event=>setValues({...values,dispute_deadline_days:event.target.value})}/></label><label className="settings-field"><span>Payment Deadline (days)</span><input type="number" min="1" max="365" value={values.payment_deadline_days||30} onChange={event=>setValues({...values,payment_deadline_days:event.target.value})}/></label></div><p className="settings-note">Confirm these periods with the applicable municipal ordinance and current enforcement policy before deployment.</p><div className="settings-actions"><button className="btn btn-primary" onClick={save} disabled={busy}>Save Deadlines</button></div></div></section>

    <section className="card settings-section"><div className="card-header"><h3 className="card-title"><Icon name="bell"/> Email Notification Settings</h3></div><div className="card-body"><div className="setting-row"><div className="setting-copy"><h4>Violation Notice Emails</h4><p>Send an email after a ticket is successfully issued when the vehicle record has an email address.</p></div><label className="toggle-wrap"><input type="checkbox" checked={checked('send_violation_notice')} onChange={event=>setValues({...values,send_violation_notice:event.target.checked?'1':'0'})}/><span>{checked('send_violation_notice')?'Enabled':'Disabled'}</span></label></div><div className="setting-row"><div className="setting-copy"><h4>Payment Confirmation Emails</h4><p>Send a confirmation after an authorized user records a valid payment.</p></div><label className="toggle-wrap"><input type="checkbox" checked={checked('send_payment_confirmation')} onChange={event=>setValues({...values,send_payment_confirmation:event.target.checked?'1':'0'})}/><span>{checked('send_payment_confirmation')?'Enabled':'Disabled'}</span></label></div><div className="settings-actions"><button className="btn btn-primary" onClick={save} disabled={busy}>Save Email Preferences</button></div></div></section>

    <section className="card settings-section" id="about-system"><div className="card-header"><h3 className="card-title">ⓘ About System</h3></div><div className="card-body"><dl className="about-system-grid"><div className="about-system-item"><dt>System Version</dt><dd>1.0.0</dd></div><div className="about-system-item"><dt>Institution</dt><dd>Bohol Island State University</dd></div><div className="about-system-item"><dt>Campus</dt><dd>Calape Campus</dd></div><div className="about-system-item"><dt>Program</dt><dd>BS Computer Science</dd></div><div className="about-system-item"><dt>Project Type</dt><dd>Academic Thesis / Capstone</dd></div><div className="about-system-item"><dt>Academic Year</dt><dd>2026–2027</dd></div></dl><p className="about-system-note">This system supports local traffic violation ticketing and record management for the study context. Official production records remain under the authority of the designated office.</p></div></section>
  </div>;
}
