import { useEffect, useState } from 'react';
import { API } from '../services/api';
import DataTable from '../components/DataTable';
import StatusBadge from '../components/StatusBadge';
import Notice from '../components/Notice';
import Modal from '../components/Modal';
import Icon from '../components/Icon';
import { firstArray, dateTime } from '../utils/format';

const blank={name:'',email:'',password:'',role:'apprehending_officer',contact_number:'',status:'active'};
export default function ManageUsers(){
 const [rows,setRows]=useState([]);const [notice,setNotice]=useState({type:'',text:''});const [open,setOpen]=useState(false);const [editing,setEditing]=useState(null);const [form,setForm]=useState(blank);const [busy,setBusy]=useState(false);
 const load=()=>API.users().then(response=>setRows(firstArray(response,['users']))).catch(error=>setNotice({type:'error',text:error.message}));useEffect(()=>{load();},[]);
 const startCreate=()=>{setEditing(null);setForm(blank);setOpen(true);};const startEdit=row=>{setEditing(row);setForm({...blank,...row,password:''});setOpen(true);};
 const save=async()=>{setBusy(true);setNotice({type:'',text:''});try{if(editing)await API.updateUser(editing.id,{name:form.name,email:form.email,role:form.role,contact_number:form.contact_number,status:form.status});else await API.createUser(form);setOpen(false);setNotice({type:'success',text:editing?'Account updated.':'Account created.'});await load();}catch(error){setNotice({type:'error',text:error.message});}finally{setBusy(false);}};
 const remove=async row=>{if(!confirm(`Permanently delete ${row.name}? Historical links can block deletion.`))return;try{await API.deleteUser(row.id);await load();}catch(error){setNotice({type:'error',text:error.message});}};
 const unlock=async row=>{try{await API.unlockUser(row.id);setNotice({type:'success',text:'Account unlocked.'});await load();}catch(error){setNotice({type:'error',text:error.message});}};
 const columns=[{key:'name',label:'Name'},{key:'email',label:'Email'},{key:'role',label:'Role',render:row=>row.role==='admin'?'Administrator':'Apprehending Officer'},{key:'status',label:'Status',render:row=><StatusBadge value={row.locked_until?'locked':row.status}/>},{key:'last_login',label:'Last login',render:row=>dateTime(row.last_login)},{key:'actions',label:'Actions',render:row=><div className="table-actions"><button className="text-link" onClick={event=>{event.stopPropagation();startEdit(row);}}>Edit</button>{row.locked_until&&<button className="text-link" onClick={event=>{event.stopPropagation();unlock(row);}}>Unlock</button>}<button className="text-link danger-link" onClick={event=>{event.stopPropagation();remove(row);}}>Delete</button></div>}];
 return <div className="restored-management-page"><Notice type={notice.type}>{notice.text}</Notice><section className="card"><div className="card-header management-card-header"><div><h3 className="card-title">User Accounts</h3><p>Administrator and Apprehending Officer accounts.</p></div><button className="btn btn-primary" onClick={startCreate}><Icon name="plus"/> Add New User</button></div><div className="card-body"><DataTable columns={columns} rows={rows}/></div></section><Modal open={open} title={editing?'Edit User':'Add New User'} onClose={()=>setOpen(false)} footer={<><button className="btn btn-secondary" onClick={()=>setOpen(false)}>Cancel</button><button className="btn btn-primary" disabled={busy} onClick={save}>{busy?'Saving…':'Save Account'}</button></>}><div className="form-grid"><label className="field"><span>Name *</span><input required value={form.name} onChange={event=>setForm({...form,name:event.target.value})}/></label><label className="field"><span>Email *</span><input type="email" required value={form.email} onChange={event=>setForm({...form,email:event.target.value})}/></label>{!editing&&<label className="field span-2"><span>Temporary password *</span><input type="password" minLength="12" required value={form.password} onChange={event=>setForm({...form,password:event.target.value})}/><small>At least 12 characters with uppercase, lowercase, number, and symbol.</small></label>}<label className="field"><span>Role</span><select value={form.role} onChange={event=>setForm({...form,role:event.target.value})}><option value="apprehending_officer">Apprehending Officer</option><option value="admin">Administrator</option></select></label><label className="field"><span>Contact number</span><input value={form.contact_number||''} onChange={event=>setForm({...form,contact_number:event.target.value})}/></label>{editing&&<label className="field"><span>Status</span><select value={form.status} onChange={event=>setForm({...form,status:event.target.value})}><option value="active">Active</option><option value="inactive">Inactive</option></select></label>}</div></Modal></div>;
}
