import { useEffect, useMemo, useState } from 'react';
import { API } from '../services/api';
import Notice from '../components/Notice';
import Icon from '../components/Icon';
import Modal from '../components/Modal';
import { dateTime, firstArray } from '../utils/format';

export default function Notifications(){
  const [rows,setRows]=useState([]);const [selected,setSelected]=useState([]);const [unreadOnly,setUnreadOnly]=useState(false);const [notice,setNotice]=useState({type:'',text:''});const [message,setMessage]=useState(null);const [messageBusy,setMessageBusy]=useState(false);
  const load=async()=>{try{const response=await API.notifications();setRows(firstArray(response,['notifications']));setSelected([]);}catch(error){setNotice({type:'error',text:error.message});}};
  useEffect(()=>{load();},[]);
  const visible=useMemo(()=>unreadOnly?rows.filter(row=>Number(row.is_read)===0):rows,[rows,unreadOnly]);
  const read=async row=>{if(Number(row.is_read)===1)return;try{await API.readNotification(row.id);await load();}catch(error){setNotice({type:'error',text:error.message});}};
  const remove=async row=>{try{await API.deleteNotification(row.id);await load();setNotice({type:'success',text:'Notification deleted.'});}catch(error){setNotice({type:'error',text:error.message});}};
  const toggle=id=>setSelected(current=>current.includes(id)?current.filter(value=>value!==id):[...current,id]);
  const allVisibleSelected=visible.length>0&&visible.every(row=>selected.includes(row.id));
  const toggleAll=()=>setSelected(allVisibleSelected?selected.filter(id=>!visible.some(row=>row.id===id)):[...new Set([...selected,...visible.map(row=>row.id)])]);
  const removeSelected=async()=>{if(!selected.length||!confirm(`Delete ${selected.length} selected notification(s)?`))return;try{await API.deleteNotifications(selected);await load();setNotice({type:'success',text:'Selected notifications deleted.'});}catch(error){setNotice({type:'error',text:error.message});}};
  const clear=async()=>{if(!confirm('Delete all your notifications?'))return;try{await API.deleteAllNotifications();await load();setNotice({type:'success',text:'All notifications deleted.'});}catch(error){setNotice({type:'error',text:error.message});}};
  const openContactMessage=async row=>{if(row.reference_type!=='contact'||!row.reference_id)return;setMessageBusy(true);setNotice({type:'',text:''});try{const response=await API.contactMessage(row.reference_id);setMessage(response.data);}catch(error){setNotice({type:'error',text:error.message});}finally{setMessageBusy(false);}};
  return <div className="restored-notifications-page"><Notice type={notice.type} onClose={()=>setNotice({type:'',text:''})}>{notice.text}</Notice><section className="card"><div className="card-header notification-header"><div><h3 className="card-title">My Notifications</h3><p>System alerts, ticket updates, and workflow messages.</p></div><div className="header-actions">{selected.length>0&&<button className="btn btn-danger btn-sm" onClick={removeSelected}>Delete Selected ({selected.length})</button>}<button className="btn btn-secondary btn-sm" onClick={clear}>Delete All</button></div></div><div className="card-body"><div className="notification-toolbar"><label className="check-field"><input type="checkbox" checked={allVisibleSelected} onChange={toggleAll}/><span>Select visible</span></label><label className="check-field"><input type="checkbox" checked={unreadOnly} onChange={event=>setUnreadOnly(event.target.checked)}/><span>Unread only</span></label><span className="muted-text"><Icon name="bell"/> {visible.length} notification(s)</span></div><div className="notification-list">{visible.length?visible.map(row=><article key={row.id} className={`notification-card ${Number(row.is_read)===0?'unread':''}`} onClick={()=>read(row)}><label className="notification-select" onClick={event=>event.stopPropagation()}><input type="checkbox" checked={selected.includes(row.id)} onChange={()=>toggle(row.id)} aria-label={`Select ${row.title}`}/></label><div className="notification-content"><span className="notification-type">{row.type}</span><h3>{row.title}</h3><p>{row.message}</p><small>{dateTime(row.created_at)}</small>{row.reference_type==='contact'&&<button type="button" className="text-link notification-view-message" disabled={messageBusy} onClick={event=>{event.stopPropagation();openContactMessage(row);}}>{messageBusy?'Loading…':'View Message'}</button>}</div><button className="icon-btn" onClick={event=>{event.stopPropagation();remove(row);}} aria-label="Delete">×</button></article>):<div className="empty-state">{unreadOnly?'No unread notifications.':'No notifications.'}</div>}</div></div></section><Modal open={Boolean(message)} title="Contact Message" onClose={()=>setMessage(null)}><dl className="contact-message-details"><div><dt>Sender name</dt><dd>{message?.full_name||'—'}</dd></div><div><dt>Sender email</dt><dd>{message?.email||'—'}</dd></div><div><dt>Subject</dt><dd>{message?.subject||'—'}</dd></div><div><dt>Submission date</dt><dd>{message?.created_at?dateTime(message.created_at):'—'}</dd></div><div><dt>Message status</dt><dd>{message?.status||'—'}</dd></div><div className="span-2"><dt>Full message</dt><dd className="contact-message-body">{message?.message||'—'}</dd></div></dl></Modal></div>;
}
