-- REVIEW ONLY. Test on an isolated database before separately authorized rollout.
-- Requires all previous migrations. No production connection is made by this file.
begin;
set local lock_timeout = '5s';
set local statement_timeout = '120s';
-- Prevent concurrent old issuance/catalog writes during the one-time backfill.
lock table public.tickets, public.violations in share row exclusive mode;

alter table public.users add column officer_rank varchar(100);
alter table public.vehicles add column vehicle_make varchar(100);
alter table public.violations add column requires_description boolean not null default false;
alter table public.tickets
  add column citation_version smallint not null default 1 check(citation_version in (1,2)),
  add column legacy_penalty_recovered boolean not null default false,
  add column driver_first_name varchar(100), add column driver_middle_name varchar(100),
  add column driver_last_name varchar(100), add column driver_address text,
  add column driver_nationality varchar(100), add column driver_email_at_issue varchar(190),
  add column license_type varchar(30), add column license_type_other varchar(100),
  add column driver_license_at_issue varchar(30),
  add column plate_at_issue varchar(20), add column vehicle_type_at_issue varchar(20),
  add column vehicle_make_at_issue varchar(100), add column officer_name_at_issue varchar(100),
  add column officer_rank_at_issue varchar(100), add column incident_date date,
  add column incident_time time, add column appearance_due_date date,
  add column violation_latitude numeric(9,6) check (violation_latitude between -90 and 90),
  add column violation_longitude numeric(9,6) check (violation_longitude between -180 and 180),
  add constraint citation_coordinates_together check ((violation_latitude is null)=(violation_longitude is null));

-- Never replace a stored historical amount. For missing snapshots, freeze the
-- pre-migration effective amount, flagged as recovered (not an original snapshot).
update public.tickets t set penalty_amount_at_issue=v.penalty_amount,legacy_penalty_recovered=true
from public.violations v where v.id=t.violation_id and t.penalty_amount_at_issue is null;

create table public.ticket_violations (
  id bigint generated by default as identity primary key,
  ticket_id bigint not null references public.tickets(id) on delete cascade,
  violation_id bigint not null references public.violations(id) on delete restrict,
  violation_code_at_issue varchar(20) not null,
  violation_name_at_issue varchar(150) not null,
  penalty_amount_at_issue numeric(10,2) not null check(penalty_amount_at_issue>=0),
  same_violation_offense_count_at_issue integer not null check(same_violation_offense_count_at_issue>0),
  description_at_issue text,
  snapshot_origin text not null check(snapshot_origin in ('issued','legacy_catalog')),
  created_at timestamptz not null default current_timestamp,
  unique(ticket_id,violation_id)
);
create index ticket_violations_violation_idx on public.ticket_violations(violation_id,ticket_id);
insert into public.ticket_violations(ticket_id,violation_id,violation_code_at_issue,violation_name_at_issue,
 penalty_amount_at_issue,same_violation_offense_count_at_issue,snapshot_origin,created_at)
select t.id,t.violation_id,v.violation_code,v.violation_name,t.penalty_amount_at_issue,
 t.same_violation_offense_count_at_issue,'legacy_catalog',t.created_at
from public.tickets t join public.violations v on v.id=t.violation_id;
alter table public.ticket_violations enable row level security;
revoke all on public.ticket_violations from public,anon,authenticated,service_role;
grant select,insert on public.ticket_violations to service_role;
grant usage,select on sequence public.ticket_violations_id_seq to service_role;

insert into public.system_settings(setting_key,setting_value,description)
values('citation_flat_penalty','150.00','Fixed penalty per selected violation; history does not increase this amount.');
create function public.tvtms_citation_penalty() returns numeric
language plpgsql stable security invoker set search_path='' as $$
declare amount numeric;
begin
 select setting_value::numeric into amount from public.system_settings where setting_key='citation_flat_penalty';
 if amount is distinct from 150.00 then raise exception 'Citation penalty configuration unavailable'; end if;
 return amount;
end; $$;
create function private.enforce_citation_catalog_penalty() returns trigger
language plpgsql security invoker set search_path='' as $$
begin
 new.penalty_amount:=public.tvtms_citation_penalty();
 if lower(trim(new.violation_name)) in ('other','others') or upper(new.violation_code) in ('OTHER','OTHERS') then
   new.requires_description:=true;
 end if;
 return new;
end; $$;
create trigger violations_flat_penalty before insert or update on public.violations
for each row execute function private.enforce_citation_catalog_penalty();
update public.violations set penalty_amount=public.tvtms_citation_penalty();
-- Old escalation rules remain intact but revised preview/issuance never use them.
update public.violations set requires_description=true
where lower(trim(violation_name)) in ('other','others') or upper(violation_code) in ('OTHER','OTHERS');

-- Align only untouched seed labels with the adviser-provided ticket. Issued
-- ticket_violations were already snapshotted above; their labels do not change.
update public.violations set violation_name='Driving without license'
where violation_code='V002' and violation_name='No License'
  and not exists(select 1 from public.violations where lower(violation_name)='driving without license');
update public.violations set violation_name='Defective lighting accessory'
where violation_code='V015' and violation_name='Defective Lights'
  and not exists(select 1 from public.violations where lower(violation_name)='defective lighting accessory');
update public.violations set violation_name='Illegal stopping & parking'
where violation_code='V008' and violation_name='Illegal Parking'
  and not exists(select 1 from public.violations where lower(violation_name)='illegal stopping & parking');
update public.violations set violation_name='Disregarding traffic signs & signals'
where violation_code='V012' and violation_name='Disregarding Traffic Signs'
  and not exists(select 1 from public.violations where lower(violation_name)='disregarding traffic signs & signals');

-- Reuse equivalent Administrator-managed entries. Do not silently reactivate
-- a disabled entry or overwrite an unrelated code: stop for catalog review.
do $catalog$
declare choice record; existing record;
begin
 for choice in select * from (values
  ('TC001','Not carrying driver''s license',array['notcarryingdriverslicense','failtocarrydriverslicense','notcarryinglicense']),
  ('TC002','Driving with delinquent or invalid driver''s license',array['drivingwithdelinquentorinvaliddriverslicense','invaliddriverslicense','delinquentdriverslicense']),
  ('TC003','Driving without license',array['drivingwithoutlicense','nolicense','drivingwithoutvalidlicense']),
  ('TC004','Defective lighting accessory',array['defectivelightingaccessory','defectivelights']),
  ('TC005','Overspeeding',array['overspeeding']),
  ('TC006','Reckless Driving',array['recklessdriving']),
  ('TC007','Hitching',array['hitching']),
  ('TC008','Driving under the influence of liquor or drugs',array['drivingundertheinfluenceofliquorordrugs','drivingundertheinfluence','drunkdriving']),
  ('TC009','Obstruction to traffic',array['obstructiontotraffic']),
  ('TC010','Illegal stopping & parking',array['illegalstoppingparking','illegalstoppingandparking','illegalparking']),
  ('TC011','Disregarding traffic signs & signals',array['disregardingtrafficsignssignals','disregardingtrafficsignsandalsignals','disregardingtrafficsigns']),
  ('TC012','Abandon/unattended vehicles or trailers on highways',array['abandonunattendedvehiclesortrailersonhighways','abandonedvehiclesonhighways']),
  ('TC013','Obstruction loading/unloading in prohibited zone',array['obstructionloadingunloadinginprohibitedzone']),
  ('TC014','Overloading',array['overloading']),
  ('TC015','Motor vehicle racing',array['motorvehicleracing']),
  ('TC016','Refusal to convey passenger',array['refusaltoconveypassenger']),
  ('TC017','Operating without permit/franchise',array['operatingwithoutpermitfranchise','operatingwithoutpermit','operatingwithoutfranchise']),
  ('TC018','Others',array['other','others'])
 ) as wanted(code,name,aliases) loop
   select id,status into existing from public.violations
   where lower(regexp_replace(violation_name,'[^[:alnum:]]','','g'))=any(choice.aliases)
   order by (status='active') desc,id limit 1;
   if found then
     if existing.status<>'active' then
       raise exception 'Citation catalog choice % exists but is inactive; review it before applying this migration',choice.name;
     end if;
   else
     if exists(select 1 from public.violations where violation_code=choice.code) then
       raise exception 'Citation catalog code % is already used by a different violation',choice.code;
     end if;
     insert into public.violations(violation_code,violation_name,penalty_amount,demerit_points,status,requires_description)
     values(choice.code,choice.name,public.tvtms_citation_penalty(),0,'active',choice.name='Others');
   end if;
 end loop;
end;
$catalog$;

create function private.protect_citation_snapshots() returns trigger
language plpgsql security invoker set search_path='' as $$
begin
 if (to_jsonb(new)-array['status','payment_date','location','remarks','updated_at'])
    is distinct from (to_jsonb(old)-array['status','payment_date','location','remarks','updated_at']) then
   raise exception 'Citation issuance snapshots are immutable' using errcode='23514';
 end if;
 return new;
end; $$;
create trigger tickets_protect_citation_snapshots before update on public.tickets
for each row execute function private.protect_citation_snapshots();
create function private.protect_citation_violation() returns trigger
language plpgsql security invoker set search_path='' as $$
begin raise exception 'Issued violation snapshots are immutable' using errcode='23514'; end; $$;
create trigger ticket_violations_immutable before update on public.ticket_violations
for each row execute function private.protect_citation_violation();

create or replace view public.ticket_details with (security_invoker=true) as
select t.id,t.ticket_number,t.date_issued,t.time_issued,t.location,t.status,t.payment_date,t.user_id,
 t.penalty_amount_at_issue as penalty_amount,t.penalty_amount_at_issue,
 coalesce(t.officer_name_at_issue,u.name)::varchar(100) as officer_name,
 coalesce(t.plate_at_issue,v.plate_number) as plate_number,
 coalesce(t.vehicle_type_at_issue,v.vehicle_type) as vehicle_type,
 coalesce(t.owner_name_at_issue,v.owner_name) as owner_name,
 coalesce(t.owner_email_at_issue,v.owner_email) as owner_email,
 coalesce(t.owner_address_at_issue,v.owner_address) as owner_address,
 case when t.citation_version=2 then t.driver_license_at_issue else v.driver_license_number end as driver_license_number,
 coalesce(items.codes,viol.violation_code)::varchar(20) as violation_code,
 coalesce(items.names,viol.violation_name)::varchar(150) as violation_name,viol.demerit_points,
 t.plate_ticket_count_at_issue,t.same_violation_offense_count_at_issue,
 t.citation_version,t.legacy_penalty_recovered,t.driver_first_name,t.driver_middle_name,t.driver_last_name,
 t.driver_address,t.driver_nationality,t.driver_email_at_issue,t.license_type,t.license_type_other,
 t.vehicle_make_at_issue,t.officer_rank_at_issue,t.incident_date,t.incident_time,t.appearance_due_date,
 t.violation_latitude,t.violation_longitude,
 coalesce(items.violations,'[]'::jsonb) as violations
from public.tickets t join public.users u on u.id=t.user_id
join public.vehicles v on v.id=t.vehicle_id join public.violations viol on viol.id=t.violation_id
left join lateral (
 select string_agg(tv.violation_code_at_issue,', ' order by tv.id) codes,
 string_agg(tv.violation_name_at_issue,'; ' order by tv.id) names,
 jsonb_agg(jsonb_build_object('violation_id',tv.violation_id,'violation_code',tv.violation_code_at_issue,
 'violation_name',tv.violation_name_at_issue,'penalty_amount',tv.penalty_amount_at_issue,
 'same_violation_offense_count_at_issue',tv.same_violation_offense_count_at_issue,
 'description',tv.description_at_issue,'snapshot_origin',tv.snapshot_origin) order by tv.id) violations
 from public.ticket_violations tv where tv.ticket_id=t.id
) items on true;

create or replace function public.tvtms_catalog_prior_offenses(p_id bigint,p_plate text)
returns jsonb language sql stable security invoker set search_path='' as $$
 select jsonb_build_object('prior_count',count(*)) from public.ticket_violations tv
 join public.tickets t on t.id=tv.ticket_id join public.vehicles v on v.id=t.vehicle_id
 where tv.violation_id=p_id and t.status<>'cancelled'
 and replace(replace(upper(coalesce(t.plate_at_issue,v.plate_number)),'-',''),' ','')=p_plate;
$$;

create function public.tvtms_citation_context(p_actor bigint) returns jsonb
language plpgsql stable security invoker set search_path='' as $$
declare actor public.users%rowtype; today date:=(current_timestamp at time zone 'Asia/Manila')::date;
begin
 select * into actor from public.users where id=p_actor and role='apprehending_officer' and status='active';
 if not found then return public.tvtms_ticket_error('FORBIDDEN','Only an active Apprehending Officer may issue citations.',403); end if;
 return jsonb_build_object('date_issued',today,'time_issued',(current_timestamp at time zone 'Asia/Manila')::time,
 'appearance_due_date',today+7,'officer_name',actor.name,'officer_rank',actor.officer_rank,'flat_penalty',public.tvtms_citation_penalty());
end; $$;

create or replace function public.tvtms_ticket_create(p_data jsonb,p_user_id bigint)
returns jsonb language plpgsql security invoker set search_path='' as $$
declare
 actor public.users%rowtype; vehicle public.vehicles%rowtype; ticket public.tickets%rowtype;
 item record; ids bigint[]; num text:=upper(trim(p_data->>'ticket_number'));
 plate text:=replace(replace(upper(trim(p_data->>'plate_number')),'-',''),' ','');
 now_manila timestamp:=current_timestamp at time zone 'Asia/Manila';
 unit numeric:=public.tvtms_citation_penalty(); count_plate integer; offense integer;
 first_offense integer; incidents jsonb:='[]'::jsonb; additional text;
begin
 select * into actor from public.users where id=p_user_id and role='apprehending_officer' and status='active' for share;
 if not found then return public.tvtms_ticket_error('FORBIDDEN','Only an active Apprehending Officer may issue citations.',403); end if;
 if num is null or num !~ '^[A-Z0-9][A-Z0-9/-]{0,29}$' or plate is null or plate !~ '^[A-Z0-9]{1,20}$'
 or coalesce(p_data->>'vehicle_type','') not in ('motorcycle','tricycle','car','truck','bus','van')
 or coalesce(length(trim(p_data->>'driver_first_name')),0) not between 1 and 100
 or coalesce(length(trim(p_data->>'driver_last_name')),0) not between 1 and 100
 or coalesce(length(trim(p_data->>'driver_address')),0) not between 1 and 2000
 or coalesce(length(trim(p_data->>'driver_nationality')),0) not between 1 and 100
 or coalesce(length(trim(p_data->>'driver_email')),0) not between 3 and 190
 or coalesce(p_data->>'driver_email','') !~* '^[^[:space:]@]+@[^[:space:]@]+\.[^[:space:]@]+$'
 or coalesce(p_data->>'license_type','') not in ('Professional','Non-Professional','Student Permit / SP','Others')
 or (p_data->>'license_type'='Others' and coalesce(length(trim(p_data->>'license_type_other')),0) not between 1 and 100)
 or coalesce(length(trim(p_data->>'vehicle_make')),0) not between 1 and 100
 or coalesce(length(trim(p_data->>'owner_name')),0) not between 1 and 100
 or coalesce(length(trim(p_data->>'owner_address')),0) not between 1 and 2000
 or coalesce(length(trim(p_data->>'location')),0) not between 1 and 200 then
 return public.tvtms_ticket_error('VALIDATION_ERROR','Complete the required citation, driver, license, vehicle and incident fields.',400); end if;
 if (p_data->>'expected_date')::date is distinct from now_manila::date then
 return public.tvtms_ticket_error('STALE_REVIEW','The issuance date changed. Refresh and review the citation again.',409); end if;
 if ((p_data->>'violation_latitude') is null)<>( (p_data->>'violation_longitude') is null ) then
 return public.tvtms_ticket_error('VALIDATION_ERROR','GPS coordinates must be supplied together.',400); end if;
 if (p_data->>'violation_latitude') is not null and
    ((p_data->>'violation_latitude')::numeric not between -90 and 90
     or (p_data->>'violation_longitude')::numeric not between -180 and 180) then
 return public.tvtms_ticket_error('VALIDATION_ERROR','GPS coordinates are outside the valid range.',400); end if;
 if jsonb_typeof(p_data->'violation_ids') is distinct from 'array' then
 return public.tvtms_ticket_error('VALIDATION_ERROR','Select at least one active violation.',400); end if;
 select array_agg(value::bigint order by value::bigint) into ids from jsonb_array_elements_text(p_data->'violation_ids');
 if coalesce(cardinality(ids),0) not between 1 and 100 or cardinality(ids)<>(select count(distinct x) from unnest(ids) x) then
 return public.tvtms_ticket_error('VALIDATION_ERROR','Select one or more distinct active violations.',400); end if;
 -- Global lock order: citation number, plate, catalog rows (sorted), vehicle.
 perform pg_catalog.pg_advisory_xact_lock(pg_catalog.hashtextextended('tvtms:citation:'||num,0));
 if exists(select 1 from public.tickets where upper(trim(ticket_number))=num) then
 return public.tvtms_ticket_error('DUPLICATE_CITATION','This citation number has already been issued.',409); end if;
 perform pg_catalog.pg_advisory_xact_lock(pg_catalog.hashtextextended('tvtms:plate:'||plate,0));
 perform id from public.violations where id=any(ids) order by id for share;
 if (select count(*) from public.violations where id=any(ids) and status='active')<>cardinality(ids) then
 return public.tvtms_ticket_error('VIOLATION_UNAVAILABLE','A selected violation is unavailable.',400); end if;
 for item in select * from public.violations where id=any(ids) order by id loop
   additional:=nullif(trim(p_data->'violation_descriptions'->>item.id::text),'');
   if item.requires_description and (additional is null or length(additional)>1000) then
   return public.tvtms_ticket_error('VALIDATION_ERROR','A selected violation requires a description (1–1000 characters).',400); end if;
   offense:=((public.tvtms_catalog_prior_offenses(item.id,plate)->>'prior_count')::integer)+1;
   first_offense:=coalesce(first_offense,offense);
   incidents:=incidents||jsonb_build_array(jsonb_build_object('id',item.id,'code',item.violation_code,
    'name',item.violation_name,'offense',offense,'description',additional));
 end loop;
 select * into vehicle from public.vehicles where replace(replace(upper(plate_number),'-',''),' ','')=plate order by id limit 1 for update;
 if not found then
   insert into public.vehicles(plate_number,vehicle_type,vehicle_make,owner_name,owner_address)
   values(plate,p_data->>'vehicle_type',p_data->>'vehicle_make',p_data->>'owner_name',p_data->>'owner_address') returning * into vehicle;
 else
   update public.vehicles set vehicle_type=p_data->>'vehicle_type',vehicle_make=p_data->>'vehicle_make',
   owner_name=p_data->>'owner_name',owner_address=p_data->>'owner_address' where id=vehicle.id;
 end if;
 insert into public.plate_ticket_sequences(normalized_plate,last_number) values(plate,1)
 on conflict(normalized_plate) do update set last_number=public.plate_ticket_sequences.last_number+1,updated_at=current_timestamp returning last_number into count_plate;
 insert into public.tickets(ticket_number,user_id,vehicle_id,violation_id,penalty_amount_at_issue,date_issued,time_issued,
 location,remarks,plate_ticket_count_at_issue,same_violation_offense_count_at_issue,citation_version,
 driver_first_name,driver_middle_name,driver_last_name,driver_address,driver_nationality,driver_email_at_issue,
 license_type,license_type_other,driver_license_at_issue,plate_at_issue,vehicle_type_at_issue,vehicle_make_at_issue,
 owner_name_at_issue,owner_address_at_issue,officer_name_at_issue,officer_rank_at_issue,incident_date,incident_time,appearance_due_date,
 violation_latitude,violation_longitude)
 values(num,p_user_id,vehicle.id,ids[1],unit*cardinality(ids),now_manila::date,now_manila::time,p_data->>'location',nullif(p_data->>'remarks',''),count_plate,first_offense,2,
 trim(p_data->>'driver_first_name'),nullif(trim(p_data->>'driver_middle_name'),''),trim(p_data->>'driver_last_name'),trim(p_data->>'driver_address'),trim(p_data->>'driver_nationality'),lower(trim(p_data->>'driver_email')),
 p_data->>'license_type',nullif(p_data->>'license_type_other',''),nullif(p_data->>'driver_license_number',''),plate,p_data->>'vehicle_type',p_data->>'vehicle_make',
 p_data->>'owner_name',p_data->>'owner_address',actor.name,actor.officer_rank,now_manila::date,now_manila::time,now_manila::date+7,
 (p_data->>'violation_latitude')::numeric,(p_data->>'violation_longitude')::numeric) returning * into ticket;
 insert into public.ticket_violations(ticket_id,violation_id,violation_code_at_issue,violation_name_at_issue,penalty_amount_at_issue,same_violation_offense_count_at_issue,description_at_issue,snapshot_origin)
 select ticket.id,(x->>'id')::bigint,x->>'code',x->>'name',unit,(x->>'offense')::integer,x->>'description','issued' from jsonb_array_elements(incidents) x;
 insert into public.ticket_status_history(ticket_id,previous_status,new_status,changed_by,reason)
 values(ticket.id,null,'issued',p_user_id,'Traffic citation issued for administrator oversight');
 insert into public.audit_logs(user_id,action,entity_type,entity_id,metadata)
 values(p_user_id,'CITATION_CREATED','tickets',ticket.id,jsonb_build_object('citationNumber',num,'violationIds',ids,'totalPenalty',ticket.penalty_amount_at_issue,'appearanceDueDate',ticket.appearance_due_date)::text);
 return jsonb_build_object('ticket',(select to_jsonb(td) from public.ticket_details td where td.id=ticket.id));
exception
 when invalid_text_representation or datetime_field_overflow or invalid_datetime_format or string_data_right_truncation or numeric_value_out_of_range then
 return public.tvtms_ticket_error('VALIDATION_ERROR','One or more citation fields are invalid.',400);
 when unique_violation then return public.tvtms_ticket_error('DUPLICATE_CITATION','This citation number has already been issued.',409);
end; $$;

revoke all on function public.tvtms_citation_penalty(), public.tvtms_citation_context(bigint) from public,anon,authenticated;
grant execute on function public.tvtms_citation_penalty(), public.tvtms_citation_context(bigint) to service_role;
revoke all on function private.enforce_citation_catalog_penalty(), private.protect_citation_snapshots(), private.protect_citation_violation() from public,anon,authenticated;
grant execute on function private.enforce_citation_catalog_penalty(), private.protect_citation_snapshots(), private.protect_citation_violation() to service_role;

create or replace function public.tvtms_ticket_email_claim(p_ticket_id bigint,p_actor_id bigint)
returns jsonb language plpgsql security invoker set search_path='' as $function$
declare t record; actor_role text; actor_status text; recipient text; ledger public.ticket_email_notifications%rowtype; ledger_found boolean:=false;
begin
  if p_ticket_id is null or p_ticket_id<=0 or p_actor_id is null or p_actor_id<=0 then return jsonb_build_object('errorCode','VALIDATION_ERROR','message','Valid ticket and actor are required.','statusCode',400); end if;
  select role,status into actor_role,actor_status from public.users where id=p_actor_id;
  if actor_status is distinct from 'active' or actor_role not in ('admin','apprehending_officer') then return jsonb_build_object('errorCode','TICKET_ACCESS_DENIED','message','Access denied.','statusCode',403); end if;
  select ti.id,ti.ticket_number,ti.user_id,coalesce(ti.plate_at_issue,v.plate_number) plate_number,td.violation_name,ti.penalty_amount_at_issue penalty_amount,ti.date_issued,ti.time_issued,ti.appearance_due_date,td.violations,nullif(trim(case when ti.citation_version=2 then ti.driver_email_at_issue else ti.owner_email_at_issue end),'') recipient
    into t from public.tickets ti join public.vehicles v on v.id=ti.vehicle_id join public.ticket_details td on td.id=ti.id where ti.id=p_ticket_id for update of ti;
  if not found then return jsonb_build_object('errorCode','TICKET_NOT_FOUND','message','Ticket not found.','statusCode',404); end if;
  if actor_role='apprehending_officer' and t.user_id<>p_actor_id then return jsonb_build_object('errorCode','TICKET_ACCESS_DENIED','message','You can only manage notifications for tickets you issued.','statusCode',403); end if;
  recipient:=lower(trim(coalesce(t.recipient,'')));
  select * into ledger from public.ticket_email_notifications where ticket_id=t.id and notification_type='ticket_issued' for update;
  ledger_found:=found;
  if ledger_found and ledger.status='accepted' then return jsonb_build_object('status','already_accepted','ticketId',t.id,'ticketNumber',t.ticket_number,'attemptCount',ledger.attempt_count); end if;
  if ledger_found and ledger.status='unknown' then return jsonb_build_object('status','unknown','ticketId',t.id,'ticketNumber',t.ticket_number,'attemptCount',ledger.attempt_count); end if;
  if ledger_found and ledger.status='sending' then
    if ledger.claimed_at is not null and ledger.claimed_at<=current_timestamp-interval '5 minutes' then
      update public.ticket_email_notifications set status='unknown',updated_at=current_timestamp,last_error_code='delivery_state_unknown',last_error_message='The prior SMTP attempt did not finalize.' where id=ledger.id returning * into ledger;
      return jsonb_build_object('status','unknown','ticketId',t.id,'ticketNumber',t.ticket_number,'attemptCount',ledger.attempt_count);
    end if;
    return jsonb_build_object('status','sending','ticketId',t.id,'ticketNumber',t.ticket_number,'attemptCount',ledger.attempt_count);
  end if;
  if recipient='' or recipient !~* '^[^[:space:]@]+@[^[:space:]@]+\.[^[:space:]@]+$' then
    if not ledger_found then insert into public.ticket_email_notifications(ticket_id,status,last_error_code,last_error_message) values(t.id,'not_applicable','missing_recipient','No valid email was recorded for this ticket.') returning * into ledger;
    else update public.ticket_email_notifications set status='not_applicable',updated_at=current_timestamp,last_error_code='missing_recipient',last_error_message='No valid email was recorded for this ticket.' where id=ledger.id returning * into ledger; end if;
    return jsonb_build_object('status','not_applicable','ticketId',t.id,'ticketNumber',t.ticket_number,'attemptCount',ledger.attempt_count);
  end if;
  if ledger_found and ledger.status='not_applicable' then return jsonb_build_object('status','not_applicable','ticketId',t.id,'ticketNumber',t.ticket_number,'attemptCount',ledger.attempt_count); end if;
  if not ledger_found then insert into public.ticket_email_notifications(ticket_id,status) values(t.id,'pending') returning * into ledger; end if;
  update public.ticket_email_notifications set status='sending',attempt_count=attempt_count+1,claimed_at=current_timestamp,last_attempt_at=current_timestamp,updated_at=current_timestamp,last_error_code=null,last_error_message=null where id=ledger.id and status in ('pending','failed') returning * into ledger;
  if not found then return jsonb_build_object('status','unknown','ticketId',t.id,'ticketNumber',t.ticket_number,'attemptCount',ledger.attempt_count); end if;
  return jsonb_build_object('status','claimed','ticketId',t.id,'ticketNumber',t.ticket_number,'recipient',recipient,'plateNumber',t.plate_number,'violationName',t.violation_name,'penaltyAmount',t.penalty_amount,'attemptCount',ledger.attempt_count,'dateIssued',t.date_issued,'timeIssued',t.time_issued,'appearanceDueDate',t.appearance_due_date,'violations',t.violations);
end;
$function$;

create function public.tvtms_public_citation_violations(p_id bigint) returns jsonb language sql stable security invoker set search_path='' as $$
 select coalesce(jsonb_agg(jsonb_build_object('violation_code',violation_code_at_issue,'violation_name',violation_name_at_issue,'penalty_amount',penalty_amount_at_issue) order by id),'[]'::jsonb) from public.ticket_violations where ticket_id=p_id;
$$;
revoke all on function public.tvtms_public_citation_violations(bigint) from public,anon,authenticated;
grant execute on function public.tvtms_public_citation_violations(bigint) to service_role;
create or replace function public.tvtms_public_lookup(p_plate text,p_ticket text)
returns jsonb language sql stable security invoker set search_path='' as $$
 select coalesce(jsonb_agg(to_jsonb(q) order by q.date_issued desc,q.ticket_number desc),'[]'::jsonb) from (
 select td.ticket_number,td.plate_number,td.vehicle_type,td.violation_code,td.violation_name,td.date_issued,td.appearance_due_date,public.tvtms_public_citation_violations(td.id) violations,td.status,td.payment_date,td.penalty_amount,
 coalesce((select setting_value::integer from public.system_settings where setting_key='dispute_deadline_days'),15) dispute_deadline_days,
 (current_timestamp at time zone 'Asia/Manila')::date-td.date_issued dispute_age_days,
 case when exists(select 1 from public.disputes d where d.ticket_id=td.id and d.status in ('submitted','under_review')) then 1 else 0 end has_open_dispute,
 exists(select 1 from public.payments recorded where recorded.ticket_id=td.id) has_recorded_payment,
 coalesce(nullif(trim(case when t.citation_version=2 then t.driver_email_at_issue else t.owner_email_at_issue end),''),'')<>'' has_notification_email,
 coalesce(p.total,0) total_paid,case when td.status='cancelled' then 0 else greatest(td.penalty_amount-coalesce(p.total,0),0) end remaining_balance,
 case when td.status='cancelled' then 'cancelled' when greatest(td.penalty_amount-coalesce(p.total,0),0)=0 then 'paid' when coalesce(p.total,0)>0 then 'partially_paid' else 'unpaid' end payment_status
 from public.ticket_details td join public.tickets t on t.id=td.id
 left join lateral (select sum(amount_paid) total from public.payments where ticket_id=td.id and payment_status<>'voided') p on true
 where (p_plate is not null or p_ticket is not null)
 and (p_plate is null or replace(replace(td.plate_number,'-',''),' ','')=p_plate)
 and (p_ticket is null or td.ticket_number=p_ticket)
 order by td.date_issued desc,td.id desc limit 100) q;
$$;
create or replace function public.tvtms_public_vehicle(p_plate text)
returns jsonb language sql stable security invoker set search_path='' as $$
 select jsonb_build_object(
 'vehicles',coalesce((select jsonb_agg(to_jsonb(v)) from (select plate_number,vehicle_type from public.vehicles where replace(replace(plate_number,'-',''),' ','')=p_plate limit 1) v),'[]'::jsonb),
 'violations',coalesce((select jsonb_agg(to_jsonb(q) order by q.date_issued desc,q.ticket_number desc) from (
 select td.ticket_number,td.plate_number,td.violation_name,td.violation_code,td.date_issued,td.appearance_due_date,public.tvtms_public_citation_violations(td.id) violations,td.status,td.penalty_amount,
 coalesce(p.total,0) total_paid,case when td.status='cancelled' then 0 else greatest(td.penalty_amount-coalesce(p.total,0),0) end remaining_balance,
 case when td.status='cancelled' then 'cancelled' when greatest(td.penalty_amount-coalesce(p.total,0),0)=0 then 'paid' when coalesce(p.total,0)>0 then 'partially_paid' else 'unpaid' end payment_status
 from public.ticket_details td
 left join lateral (select sum(amount_paid) total from public.payments where ticket_id=td.id and payment_status<>'voided') p on true
 where replace(replace(td.plate_number,'-',''),' ','')=p_plate order by td.date_issued desc,td.id desc limit 100) q),'[]'::jsonb));
$$;
create or replace function public.tvtms_catalog_vehicle_violations(p_id bigint)
returns jsonb language sql stable security invoker set search_path='' as $$
  with plate as (
    select replace(replace(upper(plate_number),'-',''),' ','') as normalized_plate
    from public.vehicles where id=p_id
  )
  select coalesce(jsonb_agg(r order by r.date_issued desc,r.time_issued desc,r.id desc),'[]'::jsonb)
  from (
    select t.id,t.ticket_number,t.date_issued,t.time_issued,t.location,t.status,
      t.plate_ticket_count_at_issue,t.same_violation_offense_count_at_issue,
      coalesce(t.penalty_amount_at_issue,v.penalty_amount) penalty_amount,
      coalesce(p.total,0) total_paid,
      case when t.status='cancelled' then 0
           else greatest(coalesce(t.penalty_amount_at_issue,v.penalty_amount)-coalesce(p.total,0),0)
      end remaining_balance,
      case when t.status='cancelled' then 'cancelled'
           when greatest(coalesce(t.penalty_amount_at_issue,v.penalty_amount)-coalesce(p.total,0),0)=0 then 'paid'
           when coalesce(p.total,0)>0 then 'partially_paid'
           else 'unpaid' end payment_status,
      td.violation_name,td.violation_code,td.demerit_points,td.violations,td.appearance_due_date
    from plate pl
    join public.vehicles tv
      on replace(replace(upper(tv.plate_number),'-',''),' ','')=pl.normalized_plate
    join public.tickets t on t.vehicle_id=tv.id
    join public.violations v on v.id=t.violation_id
    join public.ticket_details td on td.id=t.id
    left join lateral (
      select sum(amount_paid) total from public.payments
      where ticket_id=t.id and payment_status<>'voided'
    ) p on true
  ) r;
$$;
create or replace function public.tvtms_report_violation_stats(p_args jsonb default '[]'::jsonb)
returns jsonb language sql stable security invoker set search_path='' as $$
 select coalesce(jsonb_agg(to_jsonb(q)),'[]'::jsonb) from (
 select tv.violation_code_at_issue violation_code,tv.violation_name_at_issue violation_name,count(*) count,
 count(*) filter(where t.status='paid') paid_count,sum(tv.penalty_amount_at_issue) assessed_penalty
 from public.ticket_violations tv join public.tickets t on t.id=tv.ticket_id
 group by tv.violation_code_at_issue,tv.violation_name_at_issue order by count(*) desc) q;
$$;
create or replace function public.tvtms_report_top_violations(p_args jsonb default '[]'::jsonb)
returns jsonb language sql stable security invoker set search_path='' as $$
 select coalesce(jsonb_agg(to_jsonb(q)),'[]'::jsonb) from (
 select tv.violation_name_at_issue violation_name,count(*) count
 from public.ticket_violations tv join public.tickets t on t.id=tv.ticket_id
 where t.date_issued between (p_args->>0)::date and (p_args->>1)::date
 group by tv.violation_name_at_issue order by count(*) desc limit 10) q;
$$;
create or replace function public.tvtms_ticket_list(p_filters jsonb)
returns jsonb language sql stable security invoker set search_path = '' as $$
  with filtered as (
    select td.* from public.ticket_details td
    where (nullif(p_filters->>'status','') is null or td.status = p_filters->>'status')
      and (nullif(p_filters->>'dateFrom','') is null or td.date_issued >= (p_filters->>'dateFrom')::date)
      and (nullif(p_filters->>'dateTo','') is null or td.date_issued <= (p_filters->>'dateTo')::date)
      and (nullif(p_filters->>'enforcerId','') is null or td.user_id = (p_filters->>'enforcerId')::bigint)
      and (nullif(p_filters->>'officerId','') is null or td.user_id = (p_filters->>'officerId')::bigint)
      and (nullif(p_filters->>'violation','') is null or td.violations::text ilike '%' || (p_filters->>'violation') || '%' or td.violation_code ilike '%' || (p_filters->>'violation') || '%')
      and (nullif(p_filters->>'location','') is null or td.location ilike '%' || (p_filters->>'location') || '%')
      and (nullif(p_filters->>'search','') is null
        or td.ticket_number ilike '%' || (p_filters->>'search') || '%'
        or td.plate_number ilike '%' || (p_filters->>'search') || '%'
        or td.owner_name ilike '%' || (p_filters->>'search') || '%'
        or td.owner_email ilike '%' || (p_filters->>'search') || '%'
        or td.violations::text ilike '%' || (p_filters->>'search') || '%')
  ), sorted as (
    select * from filtered
    order by
      case when p_filters->>'sortOrder' = 'ASC' then
        case p_filters->>'sortBy' when 'time_issued' then time_issued::text when 'ticket_number' then ticket_number when 'status' then status when 'plate_number' then plate_number else date_issued::text end end asc,
      case when coalesce(p_filters->>'sortOrder','DESC') <> 'ASC' then
        case p_filters->>'sortBy' when 'time_issued' then time_issued::text when 'ticket_number' then ticket_number when 'status' then status when 'plate_number' then plate_number else date_issued::text end end desc,
      time_issued desc, id desc
    limit least(greatest(coalesce((p_filters->>'pageSize')::integer,20),1),100)
    offset greatest(coalesce((p_filters->>'offset')::integer,0),0)
  )
  select jsonb_build_object('tickets', coalesce((select jsonb_agg(to_jsonb(sorted)) from sorted),'[]'::jsonb), 'total', (select count(*) from filtered));
$$;

create function public.tvtms_account_update_rank(p_id bigint,p_name text,p_email text,p_role text,p_contact text,p_status text,p_rank text) returns jsonb language plpgsql security invoker set search_path='' as $$
declare result jsonb;
begin
 result:=public.tvtms_account_update(p_id,p_name,p_email,p_role,p_contact,p_status);
 if result ? 'error' then return result; end if;
 update public.users set officer_rank=nullif(trim(p_rank),'') where id=p_id;
 return result;
end; $$;
revoke all on function public.tvtms_account_update_rank(bigint,text,text,text,text,text,text) from public,anon,authenticated;
grant execute on function public.tvtms_account_update_rank(bigint,text,text,text,text,text,text) to service_role;
CREATE OR REPLACE FUNCTION public.tvtms_catalog_vehicle_by_plate(p_plate text)
RETURNS jsonb LANGUAGE sql STABLE SECURITY INVOKER SET search_path = '' AS $$
  SELECT COALESCE(pg_catalog.jsonb_agg(r), '[]'::jsonb) FROM (
    SELECT id,plate_number,vehicle_type,vehicle_make,owner_name,owner_email,owner_address,driver_license_number
    FROM public.vehicles WHERE replace(replace(upper(plate_number), '-', ''), ' ', '') = p_plate LIMIT 1
  ) r;
$$;
create or replace function public.tvtms_report_barangay(p_args jsonb default '[]'::jsonb)
returns jsonb language sql stable security invoker
set search_path = ''
set timezone = 'Asia/Manila'
as $report$
 with citations as (
   select t.id, trim(regexp_replace(lower(t.location), '^.*,', '')) barangay,
     t.status,coalesce(t.penalty_amount_at_issue,v.penalty_amount) penalty
   from public.tickets t join public.violations v on v.id=t.violation_id
   where t.location is not null and t.location<>''
 ), totals as (
   select barangay,count(*) total_tickets,
     count(*) filter(where status='paid') paid,
     count(*) filter(where status='unpaid') unpaid,
     sum(penalty) total_value
   from citations group by barangay
 ), names as (
   select c.barangay,string_agg(distinct tv.violation_name_at_issue,', ' order by tv.violation_name_at_issue) top_violations
   from citations c join public.ticket_violations tv on tv.ticket_id=c.id
   group by c.barangay
 )
 select coalesce(jsonb_agg(to_jsonb(r) order by r.total_tickets desc),'[]'::jsonb)
 from (select totals.*,names.top_violations from totals join names using(barangay)
       order by totals.total_tickets desc limit 30) r;
$report$;
create or replace function public.tvtms_report_hotspots(p_args jsonb default '[]'::jsonb)
returns jsonb language sql stable security invoker
set search_path = ''
set timezone = 'Asia/Manila'
as $report$
    select coalesce(jsonb_agg(to_jsonb(report_row)), '[]'::jsonb) from (
SELECT
                COALESCE(NULLIF(TRIM(location), ''), 'Unspecified') as location,
                COUNT(*) as total_citations,
                SUM((select count(*) from public.ticket_violations tv where tv.ticket_id=t.id)) as total_violations,
                SUM(CASE WHEN status = 'paid' THEN 1 ELSE 0 END) as paid_count,
                SUM(CASE WHEN status = 'unpaid' THEN 1 ELSE 0 END) as unpaid_count
             FROM public.tickets t
             WHERE date_issued BETWEEN (p_args->>0)::date AND (p_args->>1)::date
             GROUP BY COALESCE(NULLIF(TRIM(location), ''), 'Unspecified')
             ORDER BY total_violations DESC
             LIMIT 20
    ) report_row;
$report$;
create or replace function public.tvtms_payment_record(p_ticket_id bigint,p_receipt text,p_amount numeric,p_date date,p_method text,p_notes text,p_actor bigint)
returns jsonb language plpgsql security invoker set search_path='' as $function$
declare t record; paid numeric; penalty numeric; balance numeric; total numeric; ps text; ns text; payment_id bigint;
begin
 if not exists(select 1 from public.users where id=p_actor and role='admin' and status='active') then
 return jsonb_build_object('errorCode','ACCESS_DENIED','message','Administrator access required','statusCode',403); end if;
 if p_amount is null or p_amount<=0 or p_amount>10000000 or p_amount<>round(p_amount,2) or coalesce(length(trim(p_receipt)),0) not between 1 and 50 or p_method is null or p_method not in ('cash','gcash','maya','bank_transfer','other') or length(p_notes)>2000 then
 return jsonb_build_object('errorCode','VALIDATION_ERROR','message','Invalid payment details','statusCode',400); end if;
 if p_date is null or p_date>(current_timestamp at time zone 'Asia/Manila')::date then
 return jsonb_build_object('errorCode','INVALID_PAYMENT_DATE','message','Payment date cannot be in the future','statusCode',400); end if;
 select ti.*,coalesce(ti.penalty_amount_at_issue,v.penalty_amount) penalty,ti.owner_name_at_issue owner_name,case when ti.citation_version=2 then ti.driver_email_at_issue else ti.owner_email_at_issue end owner_email into t from public.tickets ti join public.violations v on v.id=ti.violation_id where ti.id=p_ticket_id for update of ti;
 if not found then return jsonb_build_object('errorCode','TICKET_NOT_FOUND','message','Ticket not found','statusCode',404); end if;
 if t.status='cancelled' then return jsonb_build_object('errorCode','TICKET_CANCELLED','message','Cancelled tickets cannot receive payments','statusCode',409); end if;
 if exists(select 1 from public.disputes where ticket_id=p_ticket_id and status in ('submitted','under_review')) then return jsonb_build_object('errorCode','ACTIVE_DISPUTE','message','Resolve the active dispute before recording payment','statusCode',409); end if;
 if exists(select 1 from public.payments where official_receipt_number=p_receipt) then return jsonb_build_object('errorCode','OR_NUMBER_EXISTS','message','Official receipt number already exists','statusCode',409); end if;
 select coalesce(sum(amount_paid),0) into paid from public.payments where ticket_id=p_ticket_id and payment_status<>'voided';
 penalty:=t.penalty; balance:=greatest(0,penalty-paid);
 if balance<=0 or t.status='paid' then return jsonb_build_object('errorCode','ALREADY_PAID','message','This ticket is already fully paid','statusCode',409); end if;
 if p_amount>balance+0.001 then return jsonb_build_object('errorCode','OVERPAYMENT','message','Payment exceeds the remaining balance of PHP '||to_char(balance,'FM999999990.00'),'statusCode',400); end if;
 total:=paid+p_amount; ps:=case when total+0.001>=penalty then 'full' else 'partial' end; ns:=case when ps='full' then 'paid' else 'unpaid' end;
 insert into public.payments(ticket_id,official_receipt_number,amount_paid,payment_date,payment_method,payment_status,notes,recorded_by) values(p_ticket_id,p_receipt,p_amount,p_date,p_method,ps,p_notes,p_actor) returning id into payment_id;
 update public.tickets set status=ns,payment_date=case when ps='full' then p_date else null end where id=p_ticket_id;
 insert into public.ticket_status_history(ticket_id,previous_status,new_status,changed_by,reason) values(p_ticket_id,t.status,case when ps='full' then 'paid' else 'partially_paid' end,p_actor,'Payment recorded. OR: '||p_receipt);
 return jsonb_build_object('paymentId',payment_id,'ticket',to_jsonb(t),'paymentStatus',ps,'total',total,'penalty',penalty,'nextStatus',ns);
exception when unique_violation then
 return jsonb_build_object('errorCode','OR_NUMBER_EXISTS','message','Official receipt number already exists','statusCode',409);
end;
$function$;
create or replace function public.tvtms_dispute_resolve(p_id bigint,p_status text,p_notes text,p_actor bigint)
returns jsonb language plpgsql security invoker set search_path='' as $function$
declare d record; ticket_id_value bigint;
begin
 if not exists(select 1 from public.users where id=p_actor and role='admin' and status='active') then return jsonb_build_object('errorCode','ACCESS_DENIED','message','Administrator access required','statusCode',403); end if;
 if p_status is null or p_status not in ('under_review','approved','rejected','closed') then return jsonb_build_object('errorCode','INVALID_STATUS','message','Invalid dispute status','statusCode',400); end if;
 if length(p_notes)>4000 or (p_status in ('approved','rejected','closed') and coalesce(length(trim(p_notes)),0)<5) then return jsonb_build_object('errorCode','VALIDATION_ERROR','message','Resolution notes of at least 5 characters are required','statusCode',400); end if;
 select ticket_id into ticket_id_value from public.disputes where id=p_id;
 perform 1 from public.tickets where id=ticket_id_value for update;
 select di.*,t.ticket_number,t.status ticket_status,case when t.citation_version=2 then t.driver_email_at_issue else t.owner_email_at_issue end notification_email,t.owner_name_at_issue owner_name into d from public.disputes di join public.tickets t on t.id=di.ticket_id where di.id=p_id for update of di;
 if not found then return jsonb_build_object('errorCode','DISPUTE_NOT_FOUND','message','Dispute not found','statusCode',404); end if;
 if d.status in ('approved','rejected','closed') then return jsonb_build_object('errorCode','DISPUTE_FINALIZED','message','This dispute is already finalized','statusCode',409); end if;
 if p_status='approved' and (select coalesce(sum(amount_paid),0) from public.payments where ticket_id=d.ticket_id and payment_status<>'voided')>0 then return jsonb_build_object('errorCode','PAYMENT_EXISTS','message','A dispute cannot be approved after payment has been recorded','statusCode',409); end if;
 update public.disputes set status=p_status,resolution_notes=p_notes,resolved_by=p_actor,resolved_at=case when p_status in ('approved','rejected','closed') then current_timestamp else null end where id=p_id;
 if p_status='approved' and d.ticket_status='unpaid' then
 update public.tickets set status='cancelled' where id=d.ticket_id;
 insert into public.ticket_status_history(ticket_id,previous_status,new_status,changed_by,reason,approver_id) values(d.ticket_id,'unpaid','cancelled',p_actor,'Dispute approved: '||p_notes,p_actor);
 end if;
 return jsonb_build_object('dispute',to_jsonb(d));
end;
$function$;
-- Keep public filing eligibility unchanged. For revised citations, the person
-- shown to reviewers is the cited driver, not the registered vehicle owner.
create or replace function public.tvtms_public_dispute_submit(p_ticket text,p_plate text,p_reason text)
returns jsonb language plpgsql security invoker set search_path='' as $function$
declare t public.tickets%rowtype; deadline integer; dispute_id bigint;
begin
 if coalesce(length(p_ticket),0) not between 1 and 30
    or coalesce(length(regexp_replace(trim(p_plate),'[[:space:]-]+','','g')),0) not between 1 and 30
    or coalesce(length(trim(p_reason)),0) not between 10 and 4000 then
   return jsonb_build_object('errorCode','VALIDATION_ERROR','message','Invalid ticket number or dispute reason.','statusCode',400);
 end if;
 select * into t from public.tickets where ticket_number=p_ticket for update;
 if not found then return jsonb_build_object('errorCode','TICKET_NOT_FOUND','message','Ticket not found.','statusCode',404); end if;
 if not exists(select 1 from public.vehicles where id=t.vehicle_id
     and upper(regexp_replace(trim(plate_number),'[[:space:]-]+','','g'))=upper(regexp_replace(trim(p_plate),'[[:space:]-]+','','g'))) then
   return jsonb_build_object('errorCode','TICKET_PLATE_MISMATCH','message','Ticket number and plate number do not match.','statusCode',403);
 end if;
 if exists(select 1 from public.payments where ticket_id=t.id) then
   return jsonb_build_object('errorCode','PAYMENT_EXISTS','message','Tickets with any recorded payment cannot be disputed.','statusCode',403);
 end if;
 if t.status<>'unpaid' then
   return jsonb_build_object('errorCode','INVALID_TICKET_STATUS','message','Only unpaid tickets can be disputed.','statusCode',403);
 end if;
 select coalesce((select setting_value::integer from public.system_settings where setting_key='dispute_deadline_days'),15) into deadline;
 if (current_timestamp at time zone 'Asia/Manila')::date-t.date_issued>deadline then
   return jsonb_build_object('errorCode','DISPUTE_DEADLINE_EXPIRED','message','The '||deadline||'-day dispute period has ended.','statusCode',403);
 end if;
 if exists(select 1 from public.disputes where ticket_id=t.id and status in ('submitted','under_review')) then
   return jsonb_build_object('errorCode','DISPUTE_ALREADY_EXISTS','message','A dispute is already open for this ticket.','statusCode',409);
 end if;
 insert into public.disputes(ticket_id,submitted_by,contact_name,contact_email,submission_source,reason,status)
 values(t.id,null,
   case when t.citation_version=2 then nullif(concat_ws(' ',t.driver_first_name,t.driver_middle_name,t.driver_last_name),'')
        else nullif(trim(t.owner_name_at_issue),'') end,
   case when t.citation_version=2 then nullif(trim(t.driver_email_at_issue),'')
        else nullif(trim(t.owner_email_at_issue),'') end,
   'public',trim(p_reason),'submitted') returning id into dispute_id;
 insert into public.notifications(user_id,type,title,message,reference_type,reference_id)
 select id,'dispute','Public Dispute Filed','Public dispute filed for ticket '||p_ticket,'dispute',dispute_id
 from public.users where role='admin' and status='active';
 return jsonb_build_object('disputeId',dispute_id);
end;
$function$;
revoke all on function public.tvtms_public_dispute_submit(text,text,text) from public,anon,authenticated,service_role;
grant execute on function public.tvtms_public_dispute_submit(text,text,text) to service_role;
create function private.check_citation_total() returns trigger language plpgsql security invoker set search_path='' as $$
declare tid bigint; t public.tickets%rowtype; total numeric; n integer;
begin
 if tg_table_name='tickets' then tid:=new.id; else tid:=new.ticket_id; end if;
 select * into t from public.tickets where id=tid;
 if not found or t.citation_version<>2 then return null; end if;
 select count(*),sum(penalty_amount_at_issue) into n,total from public.ticket_violations where ticket_id=tid;
 if n<1 or total is distinct from t.penalty_amount_at_issue or total<>n*public.tvtms_citation_penalty()
    or exists(select 1 from public.ticket_violations where ticket_id=tid
              and penalty_amount_at_issue<>public.tvtms_citation_penalty()) then
 raise exception 'Citation total does not match issued violations' using errcode='23514'; end if;
 return null;
end; $$;
create constraint trigger citations_total_consistent after insert on public.tickets deferrable initially deferred for each row execute function private.check_citation_total();
create constraint trigger citation_items_total_consistent after insert on public.ticket_violations deferrable initially deferred for each row execute function private.check_citation_total();
revoke all on function private.check_citation_total() from public,anon,authenticated;
grant execute on function private.check_citation_total() to service_role;

CREATE OR REPLACE FUNCTION public.tvtms_catalog_search_vehicles(p_license text, p_owner text, p_query text, p_type text)
RETURNS jsonb LANGUAGE sql STABLE SECURITY INVOKER SET search_path = '' AS $$
  SELECT COALESCE(pg_catalog.jsonb_agg(pg_catalog.to_jsonb(r) - 'sort_key' ORDER BY r.sort_key, r.id), '[]'::jsonb) FROM (
    SELECT v.id,v.plate_number,v.vehicle_type,v.owner_name,v.owner_email,v.driver_license_number,
      (SELECT count(*) FROM public.tickets t WHERE t.vehicle_id=v.id) AS violation_count,
      CASE WHEN p_license IS NULL AND p_owner IS NOT NULL THEN v.owner_name ELSE v.plate_number END AS sort_key
    FROM public.vehicles v
    WHERE CASE WHEN p_license IS NOT NULL THEN (v.driver_license_number=p_license OR EXISTS(select 1 from public.tickets t where t.vehicle_id=v.id and upper(t.driver_license_at_issue)=upper(p_license)))
      WHEN p_owner IS NOT NULL THEN v.owner_name ILIKE '%' || p_owner || '%'
      ELSE (upper(v.plate_number) LIKE '%' || upper(p_query) || '%' OR v.owner_name ILIKE '%' || p_query || '%' OR v.owner_email ILIKE '%' || p_query || '%') END
      AND (p_license IS NOT NULL OR p_type='all' OR v.vehicle_type=p_type)
    ORDER BY sort_key,v.id LIMIT 20
  ) r;
$$;
commit;
