-- Ticket email delivery ledger and public dispute email verification.
-- Review artifact only. Do not apply to production without separate approval,
-- a current backup, and a staging verification of every RPC below.

create table public.ticket_email_notifications (
  id bigint generated by default as identity primary key,
  ticket_id bigint not null references public.tickets(id) on delete restrict,
  notification_type text not null default 'ticket_issued' check (notification_type='ticket_issued'),
  status text not null default 'pending' check (status in ('pending','sending','accepted','failed','not_applicable','unknown')),
  attempt_count integer not null default 0 check (attempt_count>=0),
  claimed_at timestamptz,
  last_attempt_at timestamptz,
  accepted_at timestamptz,
  last_error_code varchar(60),
  last_error_message varchar(240),
  created_at timestamptz not null default current_timestamp,
  updated_at timestamptz not null default current_timestamp,
  unique(ticket_id,notification_type)
);

create index idx_ticket_email_notifications_status
  on public.ticket_email_notifications(status,last_attempt_at);

create table public.public_dispute_verifications (
  id bigint generated by default as identity primary key,
  ticket_id bigint not null references public.tickets(id) on delete cascade,
  challenge_token_hash char(64) not null unique,
  code_hash char(64) not null,
  requester_fingerprint char(64) not null,
  status text not null default 'pending' check (status in ('pending','verified','consumed','expired','locked')),
  attempts_remaining integer not null default 5 check (attempts_remaining between 0 and 5),
  delivery_status text not null default 'pending' check (delivery_status in ('pending','accepted','failed')),
  delivery_error_code varchar(60),
  requested_at timestamptz not null default current_timestamp,
  last_sent_at timestamptz,
  expires_at timestamptz not null,
  verified_at timestamptz,
  consumed_at timestamptz,
  created_at timestamptz not null default current_timestamp
);

create index idx_public_dispute_verifications_ticket_requested
  on public.public_dispute_verifications(ticket_id,requested_at desc);
create index idx_public_dispute_verifications_requester_requested
  on public.public_dispute_verifications(requester_fingerprint,requested_at desc);
create index idx_public_dispute_verifications_active
  on public.public_dispute_verifications(ticket_id,status,expires_at);

alter table public.ticket_email_notifications enable row level security;
alter table public.public_dispute_verifications enable row level security;

revoke all on table public.ticket_email_notifications from public, anon, authenticated, service_role;
revoke all on table public.public_dispute_verifications from public, anon, authenticated, service_role;
revoke all on sequence public.ticket_email_notifications_id_seq from public, anon, authenticated, service_role;
revoke all on sequence public.public_dispute_verifications_id_seq from public, anon, authenticated, service_role;

grant select, insert, update on table public.ticket_email_notifications to service_role;
grant select, insert, update on table public.public_dispute_verifications to service_role;
grant usage, select on sequence public.ticket_email_notifications_id_seq to service_role;
grant usage, select on sequence public.public_dispute_verifications_id_seq to service_role;

create or replace function public.tvtms_ticket_email_claim(p_ticket_id bigint,p_actor_id bigint)
returns jsonb language plpgsql security invoker set search_path='' as $function$
declare
  t record;
  actor_role text;
  actor_status text;
  recipient text;
  ledger public.ticket_email_notifications%rowtype;
  ledger_found boolean:=false;
begin
  if p_ticket_id is null or p_ticket_id<=0 or p_actor_id is null or p_actor_id<=0 then
    return jsonb_build_object('errorCode','VALIDATION_ERROR','message','Valid ticket and actor are required.','statusCode',400);
  end if;

  select role,status into actor_role,actor_status from public.users where id=p_actor_id;
  if actor_status is distinct from 'active' or actor_role not in ('admin','apprehending_officer') then
    return jsonb_build_object('errorCode','TICKET_ACCESS_DENIED','message','Access denied.','statusCode',403);
  end if;

  select ti.id,ti.ticket_number,ti.user_id,v.plate_number,viol.violation_name,
         coalesce(ti.penalty_amount_at_issue,viol.penalty_amount) penalty_amount,
         coalesce(nullif(trim(ti.owner_email_at_issue),''),nullif(trim(v.owner_email),'')) recipient
    into t
  from public.tickets ti
  join public.vehicles v on v.id=ti.vehicle_id
  join public.violations viol on viol.id=ti.violation_id
  where ti.id=p_ticket_id
  for update of ti;

  if not found then
    return jsonb_build_object('errorCode','TICKET_NOT_FOUND','message','Ticket not found.','statusCode',404);
  end if;
  if actor_role='apprehending_officer' and t.user_id<>p_actor_id then
    return jsonb_build_object('errorCode','TICKET_ACCESS_DENIED','message','You can only manage notifications for tickets you issued.','statusCode',403);
  end if;

  recipient:=lower(trim(coalesce(t.recipient,'')));
  select * into ledger from public.ticket_email_notifications
    where ticket_id=t.id and notification_type='ticket_issued' for update;
  ledger_found:=found;

  if ledger_found and ledger.status='accepted' then
    return jsonb_build_object('status','already_accepted','ticketId',t.id,'ticketNumber',t.ticket_number,'attemptCount',ledger.attempt_count);
  end if;
  if ledger_found and ledger.status='unknown' then
    return jsonb_build_object('status','unknown','ticketId',t.id,'ticketNumber',t.ticket_number,'attemptCount',ledger.attempt_count);
  end if;
  if ledger_found and ledger.status='sending' then
    if ledger.claimed_at is not null and ledger.claimed_at<=current_timestamp-interval '5 minutes' then
      update public.ticket_email_notifications set status='unknown',updated_at=current_timestamp,
        last_error_code='delivery_state_unknown',last_error_message='The prior SMTP attempt did not finalize.'
      where id=ledger.id returning * into ledger;
      return jsonb_build_object('status','unknown','ticketId',t.id,'ticketNumber',t.ticket_number,'attemptCount',ledger.attempt_count);
    end if;
    return jsonb_build_object('status','sending','ticketId',t.id,'ticketNumber',t.ticket_number,'attemptCount',ledger.attempt_count);
  end if;

  if recipient='' or recipient !~* '^[^[:space:]@]+@[^[:space:]@]+\.[^[:space:]@]+$' then
    if not ledger_found then
      insert into public.ticket_email_notifications(ticket_id,status,last_error_code,last_error_message)
      values(t.id,'not_applicable','missing_recipient','No valid email was recorded for this ticket.') returning * into ledger;
    else
      update public.ticket_email_notifications set status='not_applicable',updated_at=current_timestamp,
        last_error_code='missing_recipient',last_error_message='No valid email was recorded for this ticket.'
      where id=ledger.id returning * into ledger;
    end if;
    return jsonb_build_object('status','not_applicable','ticketId',t.id,'ticketNumber',t.ticket_number,'attemptCount',ledger.attempt_count);
  end if;

  if ledger_found and ledger.status='not_applicable' then
    return jsonb_build_object('status','not_applicable','ticketId',t.id,'ticketNumber',t.ticket_number,'attemptCount',ledger.attempt_count);
  end if;

  if not ledger_found then
    insert into public.ticket_email_notifications(ticket_id,status)
      values(t.id,'pending') returning * into ledger;
  end if;

  update public.ticket_email_notifications set status='sending',attempt_count=attempt_count+1,
    claimed_at=current_timestamp,last_attempt_at=current_timestamp,updated_at=current_timestamp,
    last_error_code=null,last_error_message=null
  where id=ledger.id and status in ('pending','failed') returning * into ledger;

  if not found then
    return jsonb_build_object('status','unknown','ticketId',t.id,'ticketNumber',t.ticket_number,'attemptCount',ledger.attempt_count);
  end if;

  return jsonb_build_object(
    'status','claimed','ticketId',t.id,'ticketNumber',t.ticket_number,
    'recipient',recipient,'plateNumber',t.plate_number,'violationName',t.violation_name,
    'penaltyAmount',t.penalty_amount,'attemptCount',ledger.attempt_count
  );
end;
$function$;

create or replace function public.tvtms_ticket_email_finalize(p_ticket_id bigint,p_status text,p_error_code text,p_error_message text)
returns jsonb language plpgsql security invoker set search_path='' as $function$
declare ledger public.ticket_email_notifications%rowtype;
begin
  if p_status not in ('accepted','failed') then
    return jsonb_build_object('errorCode','VALIDATION_ERROR','message','Invalid notification result.','statusCode',400);
  end if;
  select * into ledger from public.ticket_email_notifications
    where ticket_id=p_ticket_id and notification_type='ticket_issued' for update;
  if not found then
    return jsonb_build_object('errorCode','NOTIFICATION_NOT_FOUND','message','Notification attempt not found.','statusCode',404);
  end if;
  if ledger.status<>'sending' then
    return jsonb_build_object('errorCode','NOTIFICATION_NOT_CLAIMED','message','Notification attempt is not finalizable.','statusCode',409);
  end if;
  update public.ticket_email_notifications set status=p_status,
    accepted_at=case when p_status='accepted' then current_timestamp else null end,
    last_error_code=case when p_status='failed' then left(nullif(p_error_code,''),60) else null end,
    last_error_message=case when p_status='failed' then left(nullif(p_error_message,''),240) else null end,
    updated_at=current_timestamp
  where id=ledger.id returning * into ledger;
  return jsonb_build_object('status',ledger.status,'ticketId',ledger.ticket_id,'attemptCount',ledger.attempt_count);
end;
$function$;

create or replace function public.tvtms_dispute_verification_request(p_ticket text,p_challenge_hash text,p_code_hash text,p_requester_hash text)
returns jsonb language plpgsql security invoker set search_path='' as $function$
declare
  t record;
  deadline integer;
  recipient text;
  latest_request timestamptz;
  retry_seconds integer;
  ticket_requests integer;
  requester_requests integer;
  verification_id bigint;
begin
  if coalesce(length(p_ticket),0) not between 1 and 30
    or p_challenge_hash !~ '^[0-9a-f]{64}$'
    or p_code_hash !~ '^[0-9a-f]{64}$'
    or p_requester_hash !~ '^[0-9a-f]{64}$' then
    return jsonb_build_object('errorCode','VALIDATION_ERROR','message','Invalid verification request.','statusCode',400);
  end if;

  select ti.id,ti.ticket_number,ti.status,ti.date_issued,
         coalesce(nullif(trim(ti.owner_name_at_issue),''),nullif(trim(v.owner_name),'')) contact_name,
         coalesce(nullif(trim(ti.owner_email_at_issue),''),nullif(trim(v.owner_email),'')) contact_email
    into t
  from public.tickets ti join public.vehicles v on v.id=ti.vehicle_id
  where ti.ticket_number=p_ticket for update of ti;
  if not found then
    return jsonb_build_object('errorCode','TICKET_NOT_FOUND','message','Ticket not found.','statusCode',404);
  end if;
  if t.status<>'unpaid' then
    return jsonb_build_object('errorCode','INVALID_TICKET_STATUS','message','Only unpaid tickets can be disputed.','statusCode',403);
  end if;
  select coalesce((select setting_value::integer from public.system_settings where setting_key='dispute_deadline_days'),15) into deadline;
  if (current_timestamp at time zone 'UTC')::date-t.date_issued>deadline then
    return jsonb_build_object('errorCode','DISPUTE_DEADLINE_EXPIRED','message','The '||deadline||'-day dispute period has ended.','statusCode',403);
  end if;
  if exists(select 1 from public.disputes where ticket_id=t.id and status in ('submitted','under_review')) then
    return jsonb_build_object('errorCode','DISPUTE_ALREADY_EXISTS','message','A dispute is already open for this ticket.','statusCode',409);
  end if;

  recipient:=lower(trim(coalesce(t.contact_email,'')));
  if recipient='' or recipient !~* '^[^[:space:]@]+@[^[:space:]@]+\.[^[:space:]@]+$' then
    return jsonb_build_object('errorCode','VERIFICATION_EMAIL_UNAVAILABLE','message','No valid notification email is recorded for this ticket.','statusCode',409);
  end if;

  select greatest(requested_at,coalesce(last_sent_at,requested_at)) into latest_request
  from public.public_dispute_verifications
  where ticket_id=t.id and delivery_status in ('pending','accepted') and status in ('pending','verified')
  order by requested_at desc limit 1;
  if latest_request is not null and latest_request>current_timestamp-interval '60 seconds' then
    retry_seconds:=greatest(1,ceil(extract(epoch from (latest_request+interval '60 seconds'-current_timestamp)))::integer);
    return jsonb_build_object('errorCode','VERIFICATION_COOLDOWN','message','Please wait before requesting another verification code.','statusCode',429,'retryAfter',retry_seconds);
  end if;

  select count(*) into ticket_requests from public.public_dispute_verifications
    where ticket_id=t.id and requested_at>current_timestamp-interval '1 hour';
  select count(*) into requester_requests from public.public_dispute_verifications
    where requester_fingerprint=p_requester_hash and requested_at>current_timestamp-interval '1 hour';
  if ticket_requests>=5 or requester_requests>=5 then
    return jsonb_build_object('errorCode','VERIFICATION_RATE_LIMIT','message','Too many verification requests. Please try again later.','statusCode',429,'retryAfter',3600);
  end if;

  update public.public_dispute_verifications set status='expired'
    where ticket_id=t.id and status in ('pending','verified');
  insert into public.public_dispute_verifications(ticket_id,challenge_token_hash,code_hash,requester_fingerprint,expires_at)
    values(t.id,p_challenge_hash,p_code_hash,p_requester_hash,current_timestamp+interval '10 minutes') returning id into verification_id;

  return jsonb_build_object('status','created','verificationId',verification_id,'ticketId',t.id,
    'ticketNumber',t.ticket_number,'recipient',recipient,'expiresIn',600,'resendAfter',60);
end;
$function$;

create or replace function public.tvtms_dispute_verification_delivery(p_challenge_hash text,p_delivery_status text,p_error_code text)
returns jsonb language plpgsql security invoker set search_path='' as $function$
declare v public.public_dispute_verifications%rowtype;
begin
  if p_challenge_hash !~ '^[0-9a-f]{64}$' or p_delivery_status not in ('accepted','failed') then
    return jsonb_build_object('errorCode','VALIDATION_ERROR','message','Invalid verification delivery result.','statusCode',400);
  end if;
  select * into v from public.public_dispute_verifications where challenge_token_hash=p_challenge_hash for update;
  if not found then
    return jsonb_build_object('errorCode','VERIFICATION_NOT_FOUND','message','Verification request not found.','statusCode',404);
  end if;
  if v.status<>'pending' or v.delivery_status<>'pending' then
    return jsonb_build_object('errorCode','VERIFICATION_NOT_PENDING','message','Verification delivery is not pending.','statusCode',409);
  end if;
  update public.public_dispute_verifications set delivery_status=p_delivery_status,last_sent_at=current_timestamp,
    delivery_error_code=case when p_delivery_status='failed' then left(nullif(p_error_code,''),60) else null end,
    status=case when p_delivery_status='failed' then 'locked' else status end
  where id=v.id returning * into v;
  return jsonb_build_object('status',v.delivery_status,'ticketId',v.ticket_id);
end;
$function$;

create or replace function public.tvtms_dispute_verification_verify(p_ticket text,p_challenge_hash text,p_code_hash text)
returns jsonb language plpgsql security invoker set search_path='' as $function$
declare t public.tickets%rowtype; v public.public_dispute_verifications%rowtype; remaining integer;
begin
  if coalesce(length(p_ticket),0) not between 1 and 30 or p_challenge_hash !~ '^[0-9a-f]{64}$' or p_code_hash !~ '^[0-9a-f]{64}$' then
    return jsonb_build_object('errorCode','VALIDATION_ERROR','message','Invalid verification attempt.','statusCode',400);
  end if;
  select * into t from public.tickets where ticket_number=p_ticket for update;
  if not found then return jsonb_build_object('errorCode','VERIFICATION_FAILED','message','The verification code could not be confirmed.','statusCode',400); end if;
  select * into v from public.public_dispute_verifications where challenge_token_hash=p_challenge_hash for update;
  if not found or v.ticket_id<>t.id then
    return jsonb_build_object('errorCode','VERIFICATION_FAILED','message','The verification code could not be confirmed.','statusCode',400);
  end if;
  if v.expires_at<=current_timestamp then
    update public.public_dispute_verifications set status='expired' where id=v.id and status in ('pending','verified');
    return jsonb_build_object('errorCode','VERIFICATION_EXPIRED','message','The verification code has expired. Request a new code.','statusCode',410);
  end if;
  if v.delivery_status<>'accepted' then
    return jsonb_build_object('errorCode','VERIFICATION_NOT_DELIVERED','message','The verification code is unavailable. Request a new code.','statusCode',409);
  end if;
  if v.status='verified' then
    return jsonb_build_object('verified',true,'attemptsRemaining',v.attempts_remaining);
  end if;
  if v.status in ('consumed','expired','locked') or v.attempts_remaining<=0 then
    return jsonb_build_object('errorCode','VERIFICATION_UNAVAILABLE','message','This verification request can no longer be used.','statusCode',409);
  end if;
  if v.code_hash<>p_code_hash then
    remaining:=greatest(0,v.attempts_remaining-1);
    update public.public_dispute_verifications set attempts_remaining=remaining,
      status=case when remaining=0 then 'locked' else status end where id=v.id;
    return jsonb_build_object('errorCode','VERIFICATION_CODE_INVALID','message','The verification code is incorrect.','statusCode',400,'attemptsRemaining',remaining);
  end if;
  update public.public_dispute_verifications set status='verified',verified_at=current_timestamp where id=v.id returning * into v;
  return jsonb_build_object('verified',true,'attemptsRemaining',v.attempts_remaining);
end;
$function$;

create or replace function public.tvtms_public_dispute_verified(p_ticket text,p_challenge_hash text,p_reason text)
returns jsonb language plpgsql security invoker set search_path='' as $function$
declare
  t record;
  v public.public_dispute_verifications%rowtype;
  deadline integer;
  dispute_id bigint;
begin
  if coalesce(length(p_ticket),0) not between 1 and 30 or p_challenge_hash !~ '^[0-9a-f]{64}$'
    or coalesce(length(trim(p_reason)),0) not between 10 and 4000 then
    return jsonb_build_object('errorCode','VALIDATION_ERROR','message','Invalid ticket, verification, or dispute reason.','statusCode',400);
  end if;
  select ti.*,coalesce(nullif(trim(ti.owner_name_at_issue),''),nullif(trim(ve.owner_name),'')) contact_name,
    coalesce(nullif(trim(ti.owner_email_at_issue),''),nullif(trim(ve.owner_email),'')) contact_email
    into t from public.tickets ti join public.vehicles ve on ve.id=ti.vehicle_id
    where ti.ticket_number=p_ticket for update of ti;
  if not found then return jsonb_build_object('errorCode','TICKET_NOT_FOUND','message','Ticket not found.','statusCode',404); end if;
  select * into v from public.public_dispute_verifications where challenge_token_hash=p_challenge_hash for update;
  if not found or v.ticket_id<>t.id then
    return jsonb_build_object('errorCode','VERIFICATION_REQUIRED','message','A verified email code is required.','statusCode',403);
  end if;
  if v.status='consumed' then
    return jsonb_build_object('errorCode','VERIFICATION_ALREADY_USED','message','This verification has already been used.','statusCode',409);
  end if;
  if v.expires_at<=current_timestamp then
    update public.public_dispute_verifications set status='expired' where id=v.id and status in ('pending','verified');
    return jsonb_build_object('errorCode','VERIFICATION_EXPIRED','message','The verification has expired.','statusCode',410);
  end if;
  if v.status<>'verified' or v.delivery_status<>'accepted' then
    return jsonb_build_object('errorCode','VERIFICATION_REQUIRED','message','A verified email code is required.','statusCode',403);
  end if;
  if t.status<>'unpaid' then
    return jsonb_build_object('errorCode','INVALID_TICKET_STATUS','message','Only unpaid tickets can be disputed.','statusCode',403);
  end if;
  select coalesce((select setting_value::integer from public.system_settings where setting_key='dispute_deadline_days'),15) into deadline;
  if (current_timestamp at time zone 'UTC')::date-t.date_issued>deadline then
    return jsonb_build_object('errorCode','DISPUTE_DEADLINE_EXPIRED','message','The '||deadline||'-day dispute period has ended.','statusCode',403);
  end if;
  if exists(select 1 from public.disputes where ticket_id=t.id and status in ('submitted','under_review')) then
    return jsonb_build_object('errorCode','DISPUTE_ALREADY_EXISTS','message','A dispute is already open for this ticket.','statusCode',409);
  end if;

  insert into public.disputes(ticket_id,submitted_by,contact_name,contact_email,submission_source,reason,status)
    values(t.id,null,t.contact_name,t.contact_email,'public',trim(p_reason),'submitted') returning id into dispute_id;
  insert into public.notifications(user_id,type,title,message,reference_type,reference_id)
    select id,'dispute','Public Dispute Filed','Public dispute filed for ticket '||p_ticket,'dispute',dispute_id
    from public.users where role='admin' and status='active';
  update public.public_dispute_verifications set status='consumed',consumed_at=current_timestamp where id=v.id;
  return jsonb_build_object('disputeId',dispute_id);
end;
$function$;

revoke all on function public.tvtms_ticket_email_claim(bigint,bigint) from public, anon, authenticated, service_role;
revoke all on function public.tvtms_ticket_email_finalize(bigint,text,text,text) from public, anon, authenticated, service_role;
revoke all on function public.tvtms_dispute_verification_request(text,text,text,text) from public, anon, authenticated, service_role;
revoke all on function public.tvtms_dispute_verification_delivery(text,text,text) from public, anon, authenticated, service_role;
revoke all on function public.tvtms_dispute_verification_verify(text,text,text) from public, anon, authenticated, service_role;
revoke all on function public.tvtms_public_dispute_verified(text,text,text) from public, anon, authenticated, service_role;

grant execute on function public.tvtms_ticket_email_claim(bigint,bigint) to service_role;
grant execute on function public.tvtms_ticket_email_finalize(bigint,text,text,text) to service_role;
grant execute on function public.tvtms_dispute_verification_request(text,text,text,text) to service_role;
grant execute on function public.tvtms_dispute_verification_delivery(text,text,text) to service_role;
grant execute on function public.tvtms_dispute_verification_verify(text,text,text) to service_role;
grant execute on function public.tvtms_public_dispute_verified(text,text,text) to service_role;

-- Prevent backend code from bypassing OTP through the legacy full-email flow.
revoke execute on function public.tvtms_public_dispute(text,text) from service_role;

-- Reviewed rollback order (do not run after this feature has accepted live data):
-- 1. Revoke service_role execute on the six functions created above.
-- 2. Drop those six functions using the exact signatures above.
-- 3. Drop public.public_dispute_verifications, then public.ticket_email_notifications.
-- 4. Only when the application has also been rolled back, restore:
--    grant execute on function public.tvtms_public_dispute(text,text) to service_role;
-- Never drop or rewrite tickets, payments, disputes, users, notifications, or settings.
